# 2026 

## Blokki 1 

### Unettomuus TK-vastaanotolla (5 pistettä)

52-vuotias mies saapuu terveyskeskukseen vastaanotollesi unettomuuden vuoksi. Hänellä on pitkäaikaissairautena verenpainetauti, obesiteetti ja lisäksi hän kärsii kroonisista selkäkivuista. Potilas kertoo että hänellä on puolen vuoden ajan ollut vaikea nukahtaa ja öisin hän heräilee eikä saa enää unta. Puoliso on sanonut että potilas on ollut jo pidempään vain ”varjo entisestään”. Töissä on vaikea jaksaa olla ja keskittyä sekä töiden jälkeen on kovin uupunut. Harrastukset on jääneet hiljattain pois. Vuorokausirytmi on normaali ja potilas ei käytä alkoholia. Potilas kuvailee iltoja niin että vaikea rauhoittua nukkumaan, pitää lähteä ”takaisin tuvan puolelle”. Kertoo ohimennen että vuosi sitten tyttärellä todettiin leukemia, hoidot on olleet käynnissä ja tytär voi hyvin. Potilas on saanut työterveyslääkäriltä aikaisemmin doksepiini-reseptin unettomuuteen, mutta epäröi sitä aloittaa.
 
- a) Mitä diagnostisia vaihtoehtoja lähtisit näillä tiedoin lisäselvittämään vastaanoton aikana unettomuushäiriön lisäksi? Mainitse vähintään neljä.
- b) Potilas kysyy ”onko doksepiinia turvallista käyttää ja mitä se tekee”. Mitä vastaat hänelle?
- c) Potilas on menossa ensikäynnille unihoitajalle jonka luona olisi tarkoitus aloittaa CBT-I hoitojakso unettomuuden hoitoon. Hän kysyy sinulta ”mistä siinä hoidossa oikein on kyse”. Mitä vastaat hänelle?

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">


Ei-elimellinen unettomuus (F51.0) on diagnoosi, jota tulisi käyttää, jos potilaan vallitseva oire on unen epätyydyttävä laatu tai määrä eikä univaikeus selity muulla sairaudella. Unettomuushäiriön muut diagnostiset kriteerit kyllä täyttyvät potilaalla. Diagnostisia kriteerejä siis ovat:

<li>A: Vallitseva oire on tyytymättömyys unen määrään tai laatuun ja tämän lisäksi yksi tai useampi seuraavista oireista:</li>
  <ul>
    <li>Nukahtamisvaikeus (lapsilla tämä voi ilmetä vaikeutena nukahtaa ilman huoltajan apua)</li>
    <li>Unessa pysymisen vaikeus, joka ilmenee toistuvina heräämisinä tai vaikeutena nukahtaa yöllä uudelleen heräämisen jälkeen</li>
    <li>Herääminen aamulla liian aikaisin kykenemättä enää nukahtamaan uudelleen</li>
  </ul>

<li>B: Unihäiriö aiheuttaa kliinisesti merkittävää kärsimystä tai haittaa jollakin tärkeällä toimintakyvyn osa-alueella (esim. sosiaalinen, ammatillinen, kasvatuksellinen, akateeminen toimintakyky tai käyttäytyminen)</li>
<li>C: Univaikeus esiintyy vähintään kolmena yönä viikossa vähintään kuukauden ajan</li>
<li>D: Häiriötä ei aiheuta elimellinen, esimerkiksi neurologinen, syy tai sisätautiongelma, psyykkisiin toimintoihin vaikuttava lääkitys tai muu lääkitys</li>


Diagnostiikkaan siis kuuluu muiden syiden poissulku ja tässä huolellinen anamneesi on tärkein työkalu. Tehtävänannosta lukien potilaalla on verenpainetauti, obesiteetti ja lisäksi hän kärsii kroonisista selkäkivuista. Hän myös kuvailee väsymystä päivällä: "töiden jälkeen on kovin uupunut".

---

**Erotusdiagnostinen vaihtoehto 1: Kipu**

<li>Potilashistoriasta lukien hän kärsii kroonisista selkäkivuista. Kipu on todella yleinen unettomuuden syy – selkäkivut voivat estää rentoutumisen ja aiheuttaa heräilyä kivun vuoksi. Kivun luonteesta ja sen yhteydestä uniongelmiin tulisi kysyä.</li>



**Erotusdiagnostinen vaihtoehto 2: Masennus**

<li>Potilaan puoliso kuvailee häntä "varjoksi entisestään", harrastukset ovat jääneet ja hän kärsii uupumuksesta sekä keskittymisvaikeuksista. Nämä ovat tyypillisiä masennuksen oireita ja masennuksen klassiselle muodolle on tyypillistä uniongelmat.</li>
<li>Masennusoireista tulee kysellä enemmän ja selvittää, sopisiko oirekuva ihan masennustilaksi.</li>



**Erotusdiagnostinen vaihtoehto 3: Uniapnea**

<li>Uniapnea voi ilmetä unettomuutena (potilas herää hengityshäiriötapahtumiin).</li>
<li>STOP-BANG-pisteikköä käyttäen potilaalle tulee tarpeeksi pisteitä, joten sen mahdollisuus tulisi huomioida. Potilas on yli 50-vuotias (1p) ja mies (1p), hän on ylipainoinen (mahdollisesti 1p, BMI:tä ei ole kerrottu), hänellä on korkea verenpaine (1p) ja kokee itsensä väsyneeksi päiväaikaan (1p) -> yhteensä 4-5 pistettä pelkästään tehtävänannon perusteella ja uniapnean todennäköisyys on suuri, jos STOP-BANG on 5-8 pistettä.</li>
<li>Potilaalta tulisi siis kysellä, että kuorsaako äänekkäästi ja kysyä onko hänen vaimonsa koskaan huomauttanut hengityskatkoksista/huomannut näitä itse. Mahdollisesti potilaalle voisi algoritmisesti teettää yöpolygrafian, vaikka hengityskatkoksia ei oltaisi huomattu.</li>



**Erotusdiagnostinen vaihtoehto 4: Levottomat jalat -oireyhtymä (RLS)**

<li>Potilas kuvailee iltoja niin että vaikea rauhoittua nukkumaan ja pitää lähteä ”takaisin tuvan puolelle”.</li>
<li>Levottomien jalkojen oireyhtymällä tarkoitetaan alaraajoissa levon aikana (illalla tai yöllä) esiintyvää, vaikeasti kuvattavaa epämiellyttävää tuntemusta, joka helpottuu alaraajojen liikuttelulla. Potilaan oirekuva siis sinänsä sopii tähän. Tuntemuksista nukkumaan menon yhteydessä tulee kysyä tarkemmin ja arvioida, sopivatko oireet RLS:ään.</li>
<li>Potilaalla on myös diabetes, joten jos oirekuva sopisi RLS:ään, tulee kliinisellä tutkimuksella (turvotukset, suonikohjut, staasi-ihottuma, alaraajojen valtimoverenkierto, kosketus-, terävä- ja värinätunnot, lihaskato, lihasjänteys) sulkea pois muut sairaudet, kuten polyneuropatia, valtimo- ja laskimoinsuffisienssi.</li>



**Erotusdiagnostinen vaihtoehto 5: Ahdistuneisuushäiriö**

<li>Vaikea rauhoittua nukahtamaan ja keskittymishäiriöitä töissä. Periaatteessa nämä sopivat moniin ahdistuneisuushäiriöihin, erityisesti yleistyneeseen ahdistuneisuushäiriöön (GAD). Kannattaa kysellä yleisemmin potilaan ahdistusoireista.</li>



**Erotusdiagnostinen vaihtoehto 6: Lääkitys yms**

<li>Potilaalla on sairauksia ja mahdollisesti lääkityksiä niihin (tehtävänannossa ei mainita lääkelistaa). Potilas saattaa syödä jotain unettomuutta aiheuttavaa lääkettä, kannattaa tarkastaa lääkelista.</li>
<li>Tehtävänannossa mainitaan, että vuorokausirytmi on normaali ja potilas ei käytä alkoholia. Tämä ei kuitenkaan poissulje sitä, että potilas esimerkiksi joisi todella paljon kahvia myöhään päivälläkin, joten esim. siitä kannattaa kysyä. Samoin tulee kysyä muutenkin yleisesti unihygieniasta ja esimerkiksi selaako stimuloivaa materiaalia kännykällä sängyssä.</li>

  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

Doksepiini kuuluu trisyklisten masennuslääkkeiden (TCA) ryhmään ja on vanha lääke jo 60-luvulta. Se on yleisessä käytössä ja nykyään varsinkin uniongelmien hoidossa hyödynnetty. 

Kuten muutkin trisykliset masennuslääkkeet, doksepiini toimii kuten modernit SNRI-lääkkeet eli inhiboi noradrenaliinin ja serotoniinin pre-synaptista takaisinottoa. Kuitenkin koska unettomuuden hoidossa sitä käytetään hyvin pieninä annoksina (ex tempore-reseptillä 1-6mg), niin näitä vaikutuksia ei kliinisesti merkityksellisellä tasolla ole, vaan vaikutusmekanismi välittyy lähinnä H1-salpauksen (histamiinireseptori 1) kautta, ja tämän takia doksepiini on sedatoiva lääke. Doksepiini on tehokkaampi unen ylläpidon parantamisessa kuin nukahtamisviiveen lyhentämisessä. Se myös säilyttää unen syklit pääosin normaaleina. 

Trisyklisillä lääkkeillä myös yleisesti ottaen on muitakin vaikutuksia, kuten alfa1-salpausta (aiheuttaa klassisesti ortostaattista hypotensiota haittavaikutuksena) ja muskariinireseptorien salpausta, jonka takia on ns. antikolinergisia vaikutuksia (kuiva suu, näköhäiriöt, ummetus, virtsaretentio, hypertermia, takykardia, levottomat jalat, jopa muistiongelmia ja sekavuutta). Myös voi ilmentyä QT-ajan pidentymistä ja rytmihäiriöitä. Näitä haittavaikutuksia ei kuitenkaan käytännössä ilmene, koska annokset unilääkkeenä käytettäessä ovat niin pienet; yli 10mg annoksella tulisi kuitenkin tiedostaa haittavaikutusten lisääntymisen riski. 

Doksepiinin voi siis yleisesti katsoa olevan turvallinen lääke ja onkin yksi ainoista lääkkeistä, josta on näyttöä pidempiaikaisessakin käytössä ja se tehoaa myös kroonisessa unettomuudessa. Ei viitteitä siitä, että aiheuttaisi usein riippuvuutta tai vieroitusoireita lopettamisen yhteydessä. Pieninä annoksina se myös sopii ikääntyneille (potilas ei edes ole ikäihminen), vaikka muuten trisyklisiä välteltäisiinkin.
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="c"
          data-hide-label="c - Piilota vastaus">
    c
  </button>
  <div class="solution-content">

CBT-I = Cognitive Behavioral Therapy for Insomnia; unettomuuden lääkkeetön hoito, jolla on usein pysyvämpiä tuloksia kuin lääkkeillä ja on suhteellisen usein tehokasta; n. 60-80% saa vasteen. Voidaan toteuttaa yksilö- tai ryhmämuotoisesti sekä nettiterapiana. Terveyskeskuksissa saattaa olla unihoitajia, jotka toteuttavat CBT-I-hoitoa manualisoidun Unikoulu-menetelmän avulla.

Hoidon ytimen muodostavat **käyttäytymisterapeuttiset ja kognitiiviset menetelmät:**

<li>Käyttäytymisterapeuttisilla menetelmillä vaikutetaan unettomuutta ylläpitäviin nukkumistottumuksiin, joista keskeisimpiä ovat liiallinen vuoteessaoloaika, unirytmin epäsäännöllisyys sekä vuoteeseen ja nukkumistottumuksiin yhdistyneet negatiiviset assosiaatiot.</li>
  <ul>
    <li>**Vuoteessaoloajan rajoitusmenetelmässä** vuoteessaoloaikaa rajoitetaan siihen aikaan, joka unipäiväkirjan perusteella arvioituna pystytään tällä hetkellä nukkumaan. Vuoteessaoloaikaa lisätään vähitellen siihen asti, kunnes se vastaa unen tarvetta.</li>
    <li>**Uniärsykkeiden hallintamenetelmässä** puretaan vuoteeseen ja nukkumistottumuksiin liittyviä negatiivisia assosiaatioita siten, että vuoteeseen mennään vain uneliaana, vuodetta käytetään vain nukkumiseen (ja seksiin) ja vuoteesta poistutaan, jos nukahtaminen ei onnistu noin varttitunnissa.</li>
    <li>Molemmissa menetelmissä keskeistä on myös noudattaa säännöllistä uni-valve-rytmiä. Menetelmien käytössä on keskeistä riittävä tuki ja pitkäjänteisyys, jotta uudet hyvän unen edellytyksiä edistävät tottumukset ja myönteiset assosiaatiot vahvistuvat riittävästi.</li>
  </ul>

<li>Kognitiiviset hoitomenetelmät lisäävät keinoja unettomuutta ylläpitävän ajatuksellisen ja emotionaalisen ylivireyden käsittelemiseksi. Monet unettomat tunnistavat miettivänsä, murehtivansa tai huolehtivansa yöllä edellisen tai seuraavan päivän asioita.</li>
  <ul>
    <li>Yksi keskeinen menetelmä tämän ennaltaehkäisemiseksi on ns. **huolihetkityöskentely,** jossa varataan päivällä hetki sille, että kirjoitetaan mietityttävät asiat, huolet ja ongelmat ylös sekä tarvittaessa pyritään löytämään asioille ratkaisuja tai keinoja tulla toimeen niiden kanssa.</li>
    <li>Toinen keskeinen unettomuutta ylläpitävä tekijä ovat itse unettomuuteen liittyvät ajatukset ja tunteet, jotka pitävät vireystilan yöllä korkealla ja estävät nukahtamista tai levollista unta. Tyypillisiä ovat huoli tai pelko unettomuuden seurauksista (esim. ”Huonosti nukutun yön jälkeen en pysty keskittymään töissä”) tai nukkumiseen liitetyt suorituspaineet (”Minun on pakko pystyä nukahtamaan”). Hoidossa tehdään **kognitiivista rekonstruointia** eli tunnistetaan yksilölliset ajatukset ja tunteet sekä pyritään löytämään vaihtoehtoisia ajattelutapoja (esim. ”Huonosti nukutun yön jälkeen olen yleensä pystynyt keskittymään työhöni riittävän hyvin”). Kolmas vähemmän käytetty, mutta tehokkaaksi todettu kognitiivinen menetelmä on paradoksinen menetelmä, jossa nukkumaan mennessä pyritään pysyttelemään passiivisesti hereillä tai luovutaan unen yrittämisestä. Tavoitteena on siis luopua yrityksestä kontrolloida unta, joka haittaa luonnollisen unen toteutumista.</li>
  </ul>

  </div>
</div>


### Keskittymisvaikeuksia ja opintosuoritusten heikkenemistä opiskelijalla (5 pistettä)

22‑vuotias ammattiopiston opiskelija Oskari tulee vastaanotollesi viime kuukausina lisääntyneiden keskittymisvaikeuksien ja opintosuoritusten heikkenemisen vuoksi. Hän kertoo, että opinnoissa “ajatus ei oikein pysy kasassa” ja keskustelutilanteissa “sanoja on vaikea löytää”. Ollut yhteydessä opiskelijahuollon terveydenhoitajaan, joka ohjannut Oskarin vastaanotollesi perusterveydenhuollon yksikköön.

Erityisesti viimeisen kahden kuukauden aikana Oskari on alkanut huomata seuraavaa:

- Ajatusten omituisia katkoksia, jolloin “mieli menee tyhjäksi”.
- Epämääräistä epävarmuutta siitä, onko joku maininnut hänen nimensä julkisissa paikoissa, mutta hän ei ole varma, onko kuullut oikein.
- Hän kertoo myös, että “oma ajattelu ei ole entisenlaista”, ja hänen on vaikea luottaa siihen, että omat havainnot vastaavat todellisuutta.
- Ystävät ovat huomauttaneet, että hän vaikuttaa vetäytyneeltä ja poissaolevalta.
- Mieliala on ajoittain matalampi, mutta ei osaa tätä tarkemmin kuvata. Oskari kertoo, ettei hänellä ole aikaisempia lääkärikäyntejä. Alkoholia käyttää satunnaisesti. 
- Opiskelijajuhlissa kokeillut kerran kannabista, josta tuli “huono olo”.

Oskari on huolissaan toimintakykynsä laskusta, mutta ei itse osaa selittää, mikä on muuttunut. **Miten lähdet tutkimaan ja selvittämään Oskarin tilannetta? Pohdi diagnostisia mahdollisuuksia. Jatkotoimenpiteesi selvitystesi perusteella?**

<div class="">
  <button class="solution-button"
          data-label="Vastaus"
          data-hide-label="Piilota vastaus">
    Vastaus
  </button>
  <div class="solution-content">

Oskarin tilanteen tulisi herättää huolta, koska oirekuva – kognitiivinen heikkeneminen, ajatushäiriöt, vetäytyminen ja lievät havaintovääristymät – viittaa vahvasti alkavaan psykoottiseen prosessiin tai niin sanottuun psykoosiriskitilaan. Psykoosia siis saattaa edeltää jakso, jonka aikana esiintyy ahdistuneisuutta ja masentuneisuutta sekä lieviä psykoottisia oireita, kuten tunnetta ympäristön tai itsen muuttumisesta, seurattuna tai tarkkailtuna olemisesta tai lyhytaikaisia aistihairahduksia tai -harhoja. 22 vuoden ikä on vielä aika tyypillinen ajankohta psykoottisten häiriöiden puhkeamiselle.

Erotusdiagnostiikassa tilannetta on tarkasteltava useasta näkökulmasta:


<li>Ennakko-oireet psykoottisissa häiriöissä voivat olla todella laajalta skaalalta. Voi olla sekä epäspesifisiä psyykkisiä ja kognitiivisia oireita (kuten Oskarilla masennusta ja ajatusten salpautumista) että spesifisempiä oireita kuten vaimentuneita psykoosioireita (kuten Oskarilla positiivisista oireista aistihavaintojen vääristymiä tai epämääräistä epätodellisuuden tunnetta)</li>
<li>Todellisuudentaju on kuitenkin vielä osittain säilynyt, sillä Oskari osaa epäillä havaintojaan ja tiedostaa niiden olevan harhaisia. Kuitenkin tulee kysyä akuuteista tämänhetkisistä psykoottisista oireista tarkemmin.</li>
<li>Päihteiden käyttö tulee aina huomioida psykoosioireisilla. Hän myös kuvailee kannabiksen kokeilusta tullutta "huonoa oloa", joka nyt ei suoraan viittaa koettuun kannabispsykoosiin, mutta tulee kysellä tästä ja muustakin päihteiden käytöstä tarkemmin.</li>
<li>Mielialan alhaisuudesta tulee kysyä tarkemmin, sillä psykoottisia piirteitä voi esiintyä psykoottisessa masennuksessa. Muutenkin masennusoireet ovat usein mukana ja niiden hoito on tärkeää, vaikka onkin usein hoitoresistentimpää.</li>
<li>Samoin ahdistuneisuudesta tulee kysyä tarkemmin. Ennakko-oireisen potilaan ahdistuneisuutta tulee myös hoitaa.</li>
<li>Somaattisten syiden poissulku; infektio-oireet, neurologiset oireet, äskettäinen pään vamma... Voidaan pääasiassa poissulkea kliinisen statuksen perusteella ja anamnestisesti, jos potilas vastaa järkevästi. Kannattaa kuitenkin myös ottaa yleiset somaattiset labrat (PVK, CRP, Na, K, Krea, ALAT, THS, T4v, B12, B9, D, Gluk). Tarkemmat selvittelyt olisivat tarpeen esim. jos potilas vanhempi, taustalla merkittävä somaattinen sairaus tai olisi pääasiassa näköhallusinaatioita.</li>
<li>Itsetuhoisuudesta tulee kysyä! Jos on akuuttia itsetuhoisuutta niin päivystyksellinen hoito tarpeen.</li>


Tarkemmin oirekuvaa voi seuloa PROD-seulalla, joka on kehitetty psykoosiriskin tunnistamiseen. On kuitenkin tärkeää huomata, että pelkän lomakkeen pohjalta ei kliinisessä työssä pysty tekemään arviota psykoosin riskiryhmään kuulumisesta. Sen sijaan lomakkeella saatuja vastauksia voidaan käyttää keskustelun pohjana. Vastauksia käydään yhdessä läpi siten, että kyllävastausten yhteydessä selvitetään esimerkiksi potilaan huolestuneisuutta ja hänen oireilleen antamaansa tulkintaa

Ennakko-oireita epäiltäessä potilas on syytä ohjata erikoissairaanhoitoon arvioitavaksi. Oskarilla epäily on aika vahva, joten lähete tulee tehdä. Jos on akuuttia itsetuhoisuutta, niin pitää harkita jopa päivystyksellistä hoitoa ja tarvittaessa jopa M1-lähetteellä hoidon arvioon lähettämistä. Psykoosiriskipotilaan ensisijainen hoito on yleensä kognitiivinen käyttäytymisterapia, mutta jos oireet ovat vaikea-asteisia tai progressiivisia, psykoterapian rinnalle saatetaan aloittaa toisen polven psykoosilääke. Oheissairauksia myös hoidetaan normaaliin tapaan. Hoitolinjaukset tehdään ESH:ssa.
  </div>
</div>

### Väsymystä ja toimintakyvyn alenemista 

Vastaanotollesi terveyskeskukseen tulee 56-vuotias nainen, jolle on kertomansa mukaan ilmaantunut viimeisten kuukausien aikana voimakasta väsymystä ja alentunutta toimintakykyä. Aiempien sairauskertomustekstien perusteella hän on osa-aikainen perhepäivähoitaja,kahden nuoren aikuisen vanhempi ja avioliitossa.
Aluksi hän kertoo, ettei muista mitään eikä oikein saa tehdyksi mitään. Hän kertoo kokeneensa ajoittain mielialansa oikein surulliseksikin, mutta välillä olo on ollut täysin turta. Kertoo, että on vielä loppusyksystä touhunnut kaikenlaista harrastustoimintaa, mutta nyt kaikki on jäänyt. Töistä on suoriutunut “joten kuten”, mutta työpäivien jälkeen kertomansa mukaan on vain maannut kotona ja ruokahalu on ollut huono. Kertoo tunteneensa itsensä jatkuvasti epäonnistuneeksi.

Potilas on ulkoiselta olemukseltaan siisti ja keskustelussa vastavuoroisesti toimiva. Hänen kerrontansa on loogista ja kontakti sinänsä luontevaa. Välillä potilas unohtaa sanoja, mikä kovasti potilasta tuntuu ärsyttävän. Varsinaisia tunneilmaisuja suuntaan tai toiseen et muutoin juuri havaitse. Potilas on synkkämielisen oloinen, muttei totaalisen toivoton esim. spontaanisti kertoo odottavansa kesäloman viettoa mökillä.
 
- a)	Mainitse esitietojen pohjalta neljä erotusdiagnostista tai potilaan vointia mahdollisesti osaltaan selittävää somaattista tekijää ja kerro yhdellä tai kahdella lauseella, miten sulkisit ne pois. 
- b)	Oletetaan, että olet riittävällä varmuudella sulkenut em. syyt pois ja alat kartoittaa tilannetta psykiatrista työdiagnoosia, erotusdiagnostiikkaa ja hoidon suunnittelua varten. Mitä (annettujen esitietojen lisäksi) kysyt potilaalta ja miksi? Listaa kahdeksan mielestäsi tärkeintä asiaa lyhyin perusteluin. 
- c)	Haastattelun jälkeen sinulle on vahvistunut käsitys työdiagnoosista. Miten toteuttaisit alkuvaiheen psykoedukaation potilaalle? 


<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

Keski-ikäisellä naisella on usean kuukauden kestänyttä voimasta väsymystä, alentunutta toimintakykyä ja surullista mielialaa. Muisti on heikentynyt ja ei saa oikein mitään tehdyksi. On menettänyt kiinnostusta aikaisempaan harrastustoimintaansa. Ruokahalu on huono. Itsetunto on matala. Tämä kaikki sopii masennustilaan, mutta masennustilan diagnosoimiseen tarvitaan somaattistenkin syiden poissulku. 

**Erotusdiagnostinen vaihtoehto 1: Sydän- tai aivoinfarkti**


<li>Masennusoireet voivat usein olla näiden jälkitilan aiheuttamia. Potilaan ikä ei myöskään tee näiden mahdollisuutta niin pieneksi, että näitä voisi olla huomioimatta. Otetaan EKG (vanhojen infarktien merkit, kuten patologiset S-aallot) ja tehdään laaja neurologinen status.</li>

**Erotusdiagnostinen vaihtoehto 2: Labrat pielessä**

<li>Erityisesti hypotyreoosi tulee pitää aina mielessä -> Otetaan TSH ja T4v. </li>
<li>Potilaan iän takia on myös pidettävä mielessä vaihdevuodet, joten kysellään mm. kuukautiskierron muutoksista ja kuumista aalloista. Erotusdiagnostiikassa auttaa prolaktiinin, TSH:n ja FSH:n määritys.</li>
<li>Voitaisiin myös lisäksi ottaa ihan PVK, sillä potilaan väsymysoireisto ja tila voi ainakin olla huonompi mahdollisen anemian takia.</li>
<li>Foolihapon (B9) ja B12-vitamiinin puutos = Häiritsee neurotransmitterisynteesiä, voi nostaa homokysteiinitasoja ja vaurioittaa verisuonia, aiheuttaa aivoatrofiaa ja myeliinivaurioita yms yms -> mittaa</li>
<li>D-vitamiinin puutos</li>
<li>Metaboliset häiriöt: ALAT, Krea, Gluk</li>

**Erotusdiagnostinen vaihtoehto 3: Päihteet**

<li>On suljettava pois potilaan päihteiden käytön (esim. alkoholi, kannabis tai amfetamiini) suoraan aiheuttamat depressiot. Tämän voi usein suorittaa anamnestisesti ja pärstäkertoimella. Tarvittaessa U-Huum.</li>

**Erotusdiagnostinen vaihtoehto 4: Lääkehoito**

<li>Onko aloitettu juuri joku lääke, joka voisi latistaa mielialaa? Esimerkiksi glukokortikoidit, beetasalpaajat ja epilepsialääkkeet voivat harvinaisesti aiheuttaa masennusoireita.</li>

  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

**1 Onko ollut aiempia tällaisia jaksoja?**

<li>Toistuvassa masennuksessa ylläpitohoito on usein tarpeellista. Aikaisempien jaksojen ei tarvitse olla virallisesti diagnosoituja, mutta ne tulee selvittää vähintään anamnestisesti.</li>

**2 Onko aiemmin ollut maniaan/hypomaniaan sopivia jaksoja (onko joskus mennyt vähän vauhdikkaammin)?**

<li>Masennustilan diagnostisena kriteerinä on kaksisuuntaisen mielialahäiriön poissulku.</li>
<li>Kaksisuuntaisen mielialahäiriön diagnostiikan apuna voi käyttää aiemmin esiintyneitä maanisia oireita kartoittavaa mielialahäiriökyselyä (MDQ). Seulan positiivisuus antaa aiheen huolelliseen diagnostiseen arvioon.</li>

**3 Psyykkiset stressitekijät; esim. avioliitossa/lasten elämässä ongelmia, muuta isoa häppeningiä esim. töissä yms.?**

<li>Auttaa ymmärtämään mahdollisia reaktiivisia tekijöitä oireilun taustalla.</li>

**4 Päivittäinen toimintakyky?**

<li>Pystyykö hän huolehtimaan hygieniasta ja kodinhoidosta ja lasten kasvatuksesta? Pärjääkö kotona? Toimintakyvyttömyys tulee aina tarkasti poissulkea, koska se on päivystyksellisen hoidon tarpeen osoitus.</li>

**5 Onko itsetuhoisuutta?**

<li>Onko potilaalla kuolemanajatuksia tai suunnitelmia (tärkein turvallisuustekijä hoidon kiireellisyyden arvioimiseksi)? Itsetuhoisuudesta tulee aina muistaa kysyä!</li>

**6 Unihäiriöistä: Onko vaikeuksia nukahtaa, heräileekö hän aamuyöstä vai onko jopa liikaunisuutta?**

<li>Yksi tyypillisistä masennuksen piirteistä. Klassisessa univaikeuksia, epätyypillisessä liikaunisuutta. Yksi diagnostista kriteereistä, joita sitten ynnäilemällä voi laskea, onko potilaalla ns. vaikea masennus vai keskivaikea vai lievä.</li>
<li>Unen vaikeudet / liikaunisuus myös vaikuttaa lääkevalintaan, sillä esim. jos on vaikeaa nukahtaa niin väsyttävä lääke, kuten mirtatsapiini voisi ehkä olla paras. </li>

**7 Onko pelkoa seksuaalihaitoista tai jo entuudeltaan ongelmia sen suhteen (matala libido, ongelmia orgasmin saamisessa)?**

<li>Varsinkin SSRI-lääkkeillä on usein haittavaikutuksena seksuaaliongelmat, kuten libidon lasku ja anorgasmia. Jos potilaalla on pelkoa näistä tai jo entuudestaan ongelmaa, niin SSRI ei ole ehkä paras vaihtoehto.</li>

**8 Ahdistuneisuusoireet?**

<li>Tehtävänannossa ei mainintaa siitä, onko ahdistuneisuutta ollut. Tämä on tärkeää ja voi vaikuttaa mm. lääkehoidon valintaan ja annosteluun. SSRIt ovat hyviä, mutta ahdistuneilla potilailla usein aloitetaan pienemmällä annoksella 1. viikon ajan.</li>


**9 Aiemmat hoitokontaktit, aiempi psykoterapia, nykyinen lääkitys yms**

<li>Hoitohistorian selvittäminen tärkeää ja sitä ei aina näy potilastietojärjestelmässä.</li>
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="c"
          data-hide-label="c - Piilota vastaus">
    c
  </button>
  <div class="solution-content">

Potilaalla on todennäköisesti keskivaikea masennus (aivan kaikkia diagnostisia kriteerejä ei käyty tehtävänannossa läpi, joten sinänsä voisi olla vaikeakin, mutta potilaan kyvykkyys käydä töissä ja positiivinen tulevaisuudennäkemys huomioiden voisi olla kyseessä keskivaikea todennäköisimmin). Itse diagnoosin nimeäminen ja oireiden sopiminen diagnoosiin on osa psykoedukaatiota. Tärkeintä on siis normalisoida potilaan kokemus ja antaa nimike oireille, mikä yleensä vähentää potilaan kokemaa syyllisyyttä ("epäonnistumisen tunne"). Psykoedukaatiota tulisi pyrkiä antamaan vastaanotollakin ja voi tuoda esiin esim. seuraavia asioita:

<li>Masennus on todella yleistä, vuosiesiintyvyys aikuisväestössä ja nuorilla on noin 6 %.</li>
<li>Masennus on sairaus, ei luonteenheikkous.  Se voi oireilla psyykkisesti (mm. alakulo, ilottomuus) ja fyysisesti (mm. väsymys, univaikeudet).</li>
<li>Masennus johtuu usein tekijöiden summasta (biologia, elämäntilanne), se ei ole potilaan oma syy.</li>
<li>Hyvän hoidon ja kuntoutuksen avulla masennuksen ennuste on varsin hyvä.</li>
<li>Keskivaikeassa masennuksessa tehokkaimmat hoidot ovat psykoterapiat ja masennuslääkehoito; yhtäaikainen käyttö selvästi tehokkaampaa kuin pelkästään jommankumman -> suositellaan molempia.</li>
<li>Selitetään lääkkeistä ja niiden vaikutuksista/haittavaikutuksista ja keskustellaan lääkekokeilun halukkuudesta</li>
<li>Käydään läpi terapiamahdollisuuksia (esim. lähetteellä nettiterapia, muut lyhytterapiat)</li>
<li>Käydään läpi masennuksen omahoitomahdollisuuksia, esim. liikunnan lisääminen</li>
<li>Kaikkea vastaanotolla käytyä ei tietysti voi heti muistaa, joten ohjaus omahoito-ohjelmiin ja informaatiolähteisiin, esim. Mielenterveystalo.fi</li>
  </div>
</div>

### M1

Äiti saattaa 18-vuotiaan ikätyypillisesti pukeutuneen nuoren naisen yhteispäivystykseen ja kertoo olevansa huolissaan tyttärensä ahdistusoireista. Äiti kertoo, että nuori on ollut hyvin stressaantunut jo viime syksyn kirjoituksista alkaen ja tilanne on koko ajan pahentunut. Nuori on viettänyt jatkuvasti vähemmän aikaa kavereiden kanssa ja viime aikoina ei ole enää poistunut kotoa. Äiti kertoo, että nuori herää vasta vanhempien tullessa töistä kotiin ja vaikuttaa valvovan ja touhuavan jotain öisin. Äiti naurahtaa, että ainahan nuori on sellainen taivaanrannan maalari ollut, mutta nyt on jotenkin aiempaakin poissaolevamman oloinen.

Päätät haastatella nuoren myös ilman äitiä, sillä äidin läsnäollessa nuori antaa käytännössä äidin puhua puolestaan ja lähinnä katselee ympärilleen huoneessa. Kysyt nuorelta alkuun itsetuhoisista ajatuksista, jolloin hän vastaa ”Oon mä kyllä miettinyt elämää ja kuolemaa. Ja linnunrataa. Sitä, et miten se kaikki menee. Ja onks jotain sen takana”. Nuori puhuu hitaasti ja unenomaisesti, pitää välillä pidemmän tauon ja jatkaa ”Ja sitäkin mä oon miettinyt, et miten se kaikki käy järkeen”. Tämän jälkeen nuori vaikuttaa vaipuvan omiin ajatuksiinsa ja hetken kuluttua nousee ylös ja poistuu huoneesta. Palaa huoneeseen kuitenkin aulassa odottaneen äitinsä kanssa.

Keskustelet nuoren ja äidin kanssa hoitovaihtoehdoista. Nuori ei koe olevansa hoidon tarpeessa ja tuo esiin haluavansa takaisin kotiin lukemaan fysiikan kirjoituksiin. Lääkehoitoon liittyvään kysymykseen nuori ei vastaa. Äiti toivoo nuorelle apua ja kertoo, että nuoren saaminen päivystykseenkin oli työn ja tuskan takana.

Jos M1-lähete on mielestäsi tarpeellinen, täytä liitteenä olevaan M1-lähetteeseen kaikki tarpeelliset tiedot siten, että lähete on juridisesti pätevä ja johdonmukainen.  Jos M1-lähete ei ole mielestäsi tarpeellinen, kuvaa esseevastauksessa tahdosta riippumattoman hoidon kriteerit ja arvioi kriteerien täyttyminen nuoren kohdalla.

[Tyhjä M1-lomake](images/tyhjaM1lomake.pdf)

<div class="">
  <button class="solution-button"
          data-label="Vastaus"
          data-hide-label="Piilota vastaus">
    Vastaus
  </button>
  <div class="solution-content">

Potilas on täysi-ikäinen, joten pitää soveltaa täysi-ikäisten tahdosta riippumattoman hoidon kriteerejä: 

<li>Kaikki seuraavat kolme ehtoa täyttyvät samanaikaisesti:</li>
  <ul>
    <li>Hänen todetaan olevan mielisairas.</li>
    <li>Hän on mielisairautensa vuoksi hoidon tarpeessa siten, että hoitoon toimittamatta jättäminen olennaisesti pahentaisi hänen mielisairauttaan tai vakavasti vaarantaisi hänen terveyttään tai turvallisuuttaan tai vakavasti vaarantaisi muiden henkilöiden terveyttä tai turvallisuutta.</li>
    <li>Mitkään muut mielenterveyspalvelut eivät sovellu käytettäväksi tai ovat riittämättömiä</li>
  </ul>

Lääketieteellisesti mielisairaudella tarkoitetaan sellaista vakavaa mielenterveyden häiriötä, johon liittyy selvä todellisuudentajun häiriintyminen ja jota voidaan pitää psykoosina. Nykyisen tautiluokituksen mukaan tällaisena tilana voidaan pitää deliriumtiloja, skitsofrenian eri muotoja, elimellisiä ja muita harhaluuloisuustiloja, psykoottisia masennustiloja, kaksisuuntaisia mielialahäiriöitä, muistisairauksien vaikea-asteisia ilmenemismuotoja sekä muita psykooseja kuten orgaaniset psykoosit ja päihteiden käytön aiheuttamat psykoottiset tilat. 

Potilaalla voi epäillä psykoositasoista sairautta, sillä hänellä on siihen sopiva anamneesi ja oirekuva: yöllinen touhuaminen, mystinen ajattelu, merkittävä vastauslatenssi (negatiivinen skitsofrenian oire), asosialiteetti (negatiivinen skitsofrenian oire) ja hänen puheensa on hajanaista (positiivinen skitsofrenian oire). Hän myös vastailee mystisesti (deluusioita?). Ilman asianmukaista hoitoa psykoosisairaudet pahenevat. Hän ei myöskään hyväksy vapaaehtoista hoitoa -> M1-lähetteen kriteerit täyttyvät ja on tarpeellinen. 

Tässä alla on täytetty M1-lomake, joka toimisi itsestään tenttivastauksena. Käytännössä "Hoidon tarve"-kohdassa tarvitsee täyttää vähintään yksi kohta eikä, mutta olen nyt perustellut lomakkeeseen kaksi syytä.

[M1-lähete](images/M1-lomake.pdf)

---

Tenttivastauksen ulkopuolelta 

On tärkeää huomata, että M1-lähetettä tehdessä potilasta ei siis lähetetä suoraan tahdosta riippumattomaan hoitoon, vaan hänet lähetetään _psykiatriseen arvioon_ tahdosta riippumatta. M1-lähetteen tekijän ei siis tule olla täysin varma siitä, että potilaalla olisi mielisairaus - epäily siitä riittää! Päivystäjä haastattelee potilaan ja arvioi, täyttyvätkö tahdosta riippumattoman hoidon perusteet todennäköisesti. Jos täyttyvät todennäköisesti, niin potilas otetaan tarkkailuun. Tarkkailuaika on korkeintaan hoitoontulopäivä + 4 päivää -> Tarkkailun päätteeksi osastonlääkäri tekee M2-lausunnon (kriteerien perusteet ovat samat kuin M1-lähetteessä). M2 perustellaan huolellisesti, täyttyvätkö edellytykset tahdosta riippumattomalle sairaalahoidolle. Lisäksi selvitetään potilaan oma mielipide hoidon tarpeesta. Mikäli edellytykset täyttyvät, tekee psykiatrisesta hoidosta vastaava ylilääkäri hoitoonmääräämispäätöksen M3, jossa otetaan yksiselitteinen kanta, määrätäänkö potilas tahdosta riippumattomaan hoitoon vai ei. Tahdosta riippumatonta hoitoa voidaan jatkaa M3-päätöksellä korkeintaan 3 kuukautta. Eli prosessi on M1->tarkkailu->M2->M3. M1-lähetteen tekijä (usein TK-lääkäri) arvioi, täyttyvätkö tahdosta riippumattoman hoidon kriteerit todennäköisesti eli epäily riittää. Varmuuden odotetaan kasvavan M-prosessin edetessä. 

  </div>
</div>

## Blokki 2 

### Hiisaajalla ahdistusta

Vastaanotollesi saapuu juuri täysi-ikäistynyt potilas. Ajanvarauksen syyksi on kirjattu ahdistus ja paniikkikohtaukset. Potilasta tarkemmin haastatellessasi käy ilmi, että potilas on alkanut polttaa kannabista kaverinsa kehotuksesta noin puoli vuotta sitten. Kuvaa saaneensa sen avulla nukuttua ja rentouduttua aiempaa paremmin. 

 Haastattelua jatkaessa käy ilmi, että vaikka potilas on sinänsä kokenut unensaannin parantuneen ja olotilan rentoutuneen kannabiksen käytön myötä, aiemmat harrastukset jääneet ja toimintakyky tuntunut jollain lailla laskeneen. Potilas viettänyt päivät lähinnä kotioloissa. Lisäksi potilas tuo esiin, että on viime aikoina alkanut kärsiä paniikinomaisista ahdistuskohtauksista, joiden takia hän on joutunut usein aloittamaan kannabiksen polttamisen jo aamulla. 

 Potilaalla ei ole aiemmin ollut samankaltaista ahdistusta eikä muutoinkaan psykiatrista hoitohistoriaa. Hän kuvaa olonsa olleen varsinkin viimeisen viikon aikana kokonaisvaltaisen heikko ja jonkinlaista huimaustakin alkanut ilmetä. Ajankohtaisesti potilas kuvaa oloaan lievästi ärtyneeksi ja levottomaksi.

- a. Mitä esitietoja haluaisit vielä tarkentaa ja millaisia tutkimuksia mahdollisesti ohjelmoisit?
- b. Minkä asetat työdiagnoosiksi ja millaisen hoitosuunnitelman laadit?
- c. Potilas kysyy vielä vastaanoton lopuksi, voisiko korvaushoidosta olla apua tilanteessa. Mitä vastaat?



<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

<li>Yleinen päihdehistoria ja käyttö tarkemmin: alkoholi, tupakka, muut päihteet? Kuinka usein käyttää? Kuinka paljon käyttää? Mitä käyttää (esim. mitä juo, jos juo alkoholia)? Onko käyttö muuttunut joskus? Onko yrittänyt joskus vähentää ja epäonnistunut tässä? Miksi käyttää? Miksi ei lopeta?</li>
<li>Kannabiksen käytöstä tarkemmin: CAST-seulan avulla voi ohjata keskustelua ja kerätä vertailupisteitä myöhempää varten, mutta yleisesti voi kysyä mm: Missä muodossa käyttää (polttaako vain vai käyttääkö muita muotoja, kuten hashis, öljyt, synteettiset yms)? Käyttääkö joka päivä? Kuinka paljon käyttää, kun käyttää? Onko usein koko päivän pilvessä vai kuinka kauan? Ovatko yksittäiset annokset kasvaneet käytön mittaa - kokeeko samaa hyötyä enää samoista annoksista kuin alussa? Onko joskus yrittänyt vähentää käyttöä - epäonnistuiko/vai onnistuiko se (jos epäonnistui niin miksi)? Kokeeko käytön pakonomaiseksi? Kuinka paljon aikaa menee kannabiksen käytön ajatteluun tai sen hankkimiseen? Mitä itse ajattelee kannabiksen käytöstään?</li>
<li>Aiemmista oireista enemmän: Millainen vointi ja uni oli ennen kannabiksen käytön aloittamista ja miksi koki tarvetta kannabikselle? Onko ennen ollut ahdistuneisuutta (tehtävänannossa sanotaan, että samankaltaista ei ole ollut, mutta onko jonkinlaista ollut ennen)? Paniikkikohtauksia? Onko joskus ollut masennukseen viittaavaa? Onko ollut jaksoja, jolloin on mennyt vauhdikkaammin?</li>
<li>Nykyoireista: Missä yhteyksissä ahdistuskohtaukset tulevat - tulevatko säännöllisesti vieroitusoiremaisesti, kun ei ole hetkeen polttanut? Kuvaile ahdistuskohtauksia tarkemmin: onko niissä minkälaisia oireita? Mitä tarkoitat heikolla ololla? Millainen on huimausoire tällä hetkellä? Onko mitään fyysisiä vieroitusoireita (hikoilu, vapina)? Onko kokenut mitään psykoottista (ajatuksia, jotka eivät ole omia, onko epäillyt joitain ihmisiä tarpeettomasti, muuta outoa) niin vaikutuksenalaisena kuin selvin päin? Miksi harrastukset jääneet?</li>
<li>Sukuhistoria: Onko perheessä päihdeongelmia? Psykoosisairauksia? Muuta psykiatrista historiaa?</li>
<li>Itsetuhoisuutta? (kysytään suoraan mm. ajatuksista ja suunnitelmista ja tarvittaessa tarkempi selvittely)</li>
<li>Tukijoukot: Millainen sosiaalinen ympäristö? Voisiko saada tukea päihteidenkäytön lopettamiseen joltain?</li>
<li>Nopea status huimauksen suhteen: onko mitään korvaperäiseen tai vaaralliseen sentraaliseen huimaukseen viittaavaa?</li>

---

Tutkimuksina peruslabrat somaattisten syiden poissulkemiseksi (PVK, Na, K, Gluk, TSH, Krea, ALAT...). Huumeseula jos epäilyä sekakäytöstä. EKG jos kuvaa tykytyksiä tai rintatuntemuksia. 
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

Työdiagnoosi on kannabisriippuvuus, koska sen diagnostiset kriteerit täyttyvät 

Potilaalla on yli 1kk säännöllistä käyttöä ja riippuvuuden piirteitä tarpeeksi (tarvitaan 3/6): 

<li>Toleranssia todennäköisesti kehittynyt</li>
<li>Kontrollin menetystä ei nyt suoraan näy, mutta voi kysellä vähentämisyrityksistä ja näiden epäonnistumisista</li>
<li>Pakonomaisuudesta voi kysellä enemmän, mahdollisesti sitäkin</li>
<li>Vieroitusoireita on (ärtynyt, rebound-ahdistus, levottomuus)</li>
<li>Ajankäyttö (kuluttaa suuren osan päivästä käyttämiseen)</li>
<li>Käyttö jatkuu haitoista huolimatta (toimintakyky laskenut, harrastukset jääneet)</li>

---

Hoitosuunnitelmana on motivoivan haastattelun kautta käytön vähentämisen ja jopa lopettamisen ajaminen eteenpäin. Haastattelussa on tärkeää saada potilas itse motivoitumaan tämän tarpeesta, koska muuten se ei tule onnistumaan. Potilas myös itse asettaa omat tavoitteensa, mikä lisää sitoutumista hoitoon. 

Riippuen siitä, minkälainen suunnitelma potilaan kanssa sovitaan käytön vähentämisen/lopettamisen suhteen, niin sovitaan myös tarvittavista tukitoimista. Aina tulee ehdottaa omahoito-ohjeita mm. Mielenterveystalolta tai muilta nettisivuilta. Näiltä myös löytyy paljon psykoedukaatiomateriaalia, jota potilaan kannattaa lukea. Jo vastaanotolla kannattaa antaa psykoedukaatiota kannabiksen haitoista (kognitiivisesti heikentävät vaikutukset (voi myös motivoida sillä, että todennäköisesti palautuvat n. kuukauden sisällä käytön lopetuksesta), amotivaatio, vieroitusoireet, psykoosiriski, mahdollisesti muidenkin mielenterveyshäiriöiden (esim. masennus) riski koholla) ja peilata niitä potilaan nykytilanteeseenkin. 

Potilaan kanssa tulee myös sopia kontrollikäynneistä: joko sitten hoitajalla tai lääkärillä. Kontrollikäynneillä seurataan suunnitelmaan sitoutumista, sen etenemistä ja mahdollisia tarvittavia muutoksia. 

Voidaan myös ehdottaa käymistä ryhmissä, kuten A-killassa ja siten saada hyvin tehokasta vertaistukea käytön vähentämiseen/lopettamiseen. 

Vieroitusoireiden hoidossa oireenmukainen hoito: pahoinvointiin esim. metoklopramidi, jos takykardiaa yms. -> beetasalpaaja ... Vieroitusoireet voivat jatkua jopa n. 2-6vk kannabiksen käytön loputtua. 
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="c"
          data-hide-label="c - Piilota vastaus">
    c
  </button>
  <div class="solution-content">

Korvaushoito tarkoittaa riippuvuuden hoitoa jatkuvalla kontrolloidulla korvaavan aineen annostelulla ja korvaushoito voi jatkua hyvinkin pitkään eikä sen tarkoituksena ole aina päästä eroon korvaushoidostakaan (vaikka tämä voi myös olla tavoite). Suomessa korvaushoitoa on käytössä pääasiassa vain opioidiriippuvuuden hoidossa eikä muiden riippuvuuksien hoitoon se yleensä kuulu, vaan niiden yhteydessä harrastetaan vieroitushoitoa, jonka tarkoituksena on vieroitusoireita hoitamalla ja psykososiaalista tukea antamalla mahdollistaa päihteenkäytöstä vieroittuminen. Esimerkiksi siis bentsoriippuvuudessa ajetaan bentsot alas laskemalla annoksia suunnitelmallisesti. Alkoholiriippuvuudessa vieroitusoireita hoidetaan bentsoilla, jotka myös ajetaan alas vieroitusoireiden mukaan. Kannabisriippuvuudessa oireita hoidetaan oireenmukaisesti, samoin kuten stimulanttiriippuvuudessa. 

  </div>
</div>

### Potilas epäilee ADHD:ta itsellään

Terveyskeskusvastaanotollesi saapuu 27-vuotias nainen, jolle on kirjattu tulosyyksi ADHD-epäily. Tarkistat potilaskertomustekstit ennen vastaanoton alkua, josta käy ilmi potilaan käyneen 18-19-vuotiaana useita kertoja päivystyksessä viiltelyn ja itsetuhoisten ajatusten vuoksi - usein päihtyneenä. Potilaalle oli aloitettu psykiatrian hoitokontakti, mutta tämä siirtyi toiselle paikkakunnalle potilaan muutettua opintojen vuoksi. Potilas kertoo, että hänelle on asetettu "epävakaan persoonallisuuden, kompleksin traumatisaation ja tyypin II kaksisuuntaisen diagnoosit". Näihin liittyviä kertomustekstejä hän ei haluaisi luovuttaa laajemmin, koska niihin on kirjattu hänen traumakokemuksiaan. Potilas kokee toipuneensa näistä kuitenkin lääkehoidon ja psykoterapian avulla siten, että esh-kontakti päätetty, ja potilas on jättänyt lääkitykset pois n. 6kk sitten. Potilas muutti vajaa vuosi sitten takaisin kotipaikkakunnalleen saatuaan yliopistotutkinnon suoritettua, ja nyt hakee tutkintonsa mukaista työtä. Huomannut työnhaussa enenevästi vaikeuksia keskittymisongelmien ja hakemusten laatimisen aloittamisen vaikeuden vuoksi. Potilas epäilee, että hänellä on ADD, ja haluaisi tähän lääkehoitoa mahdollisimman pian, jotta voisi jatkaa työn hakemista. Potilas pyytää kiireellistä arviota, koska keskittymisvaikeudet ovat vieneet voimavarat täysin ja aiheuttanut unettomuutta.

- a. Laadi lyhyt erotusdiagnoosilista potilaan oireita todennäköisimmin selittävistä syistä
- b. Mitä lisätietoja tarvitset ja miksi?
- c. Miten kerrot potilaalle ADHD:n tyypillisestä tutkimusprosessista ja työnjaosta erikoissairaanhoidon ja perusterveydenhuollon välillä?
- d. Mitä vastaat potilaan ADD-lääkityspyyntöön?
- e. Laadi perusterveydenhuollon toimintaan soveltuva suunnitelma ja perustele sen sisältö


<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

ADHD, bipolaarihäiriönsä masennustila tai hypomania, ahdistuneisuushäiriö, päihdehäiriö, elämän stressi ja ei-elimellinen unettomuus, uniapnea, sopeutumishäiriö, somaattiset syyt (anemia, kilpirauhashäiriöt, vitamiinipuutokset (b12, b9, d), metaboliset häiriöt (diabetes, maksan/munuaisten vajaatoiminta) 
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

<li>Somaattiset sairaudet? Onko kroonista kipua yms</li>
  <ul>
    <li>Tärkeitä unettomuuden syitä</li>
    <li>Labroista voi ottaa mm. PVKT (anemia), TSH, T4v (kilpirauhashäiriöt, erityisesti hypotyreoosi), ALAT, ASAT, GT (maksan vajaatoiminta), Krea, K, Na, Ca (munuaisten vajaatoiminta ja elektrolyyttihäiriöt), CRP (jos krooniseen tulehdussairaukseen viittaavaa tarkemmassa anamneesisssa/statuksessa), vitamiinit (D, B12, B9)</li>
  </ul>
<li>Onko vielä psykiatrista hoitokontaktia ja kontrolloidaanko aikaisempia sairauksia miten? Mahdollisesti suostuttelun kautta aikaisempien tekstien lukulupa.</li>
<li>Unettomuuden tarkempi selvittely: Kuinka kauan kestänyt? Minkä tyyppinen unihäiriö on: vaikeus nukahtaa/heräilyä yöllä/liian aikainen herääminen? Kuinka paljon arvioi saavansa unta? Onko dataa älykellosta yms? Mitä itse ajattelee olevan unettomuuden taustalla (ajatuksen nukahtaessa yms)? Onko joku joskus kertonut hengityskatkoksista? Onko käyttänyt joskus jotain lääkkeitä/itse lääkinnyt itseään esim. alkoholilla unta varten? Millaista uni oli ennen työnhakua? Unihygienia (säännöllisyys, mitä tekee sängyssä yms).</li>
<li>Muutenkin uniapnean riskin arviointi STOP-BANG:in kautta (kuorsaako, onko väsymystä, onko joku sanonut hengityskatkoksista, verenpaineet, bmi (>35), ikä, kaulan ympärysmitta, sukupuoli (M)). Potilas saa pelkästään tehtävänannon perusteella ehkä vain 1 pisteen (väsymys), mutta tarkemmalla selvittelyllä pisteet voisivat nousta korkeammiksi. Tarvittaessa sitten yöpolygrafiaselvittelyt.</li>
<li>Millaisena kokee mielialansa nyt, masennuksen oireista kysyminen: mieliala, kiinnostuksen väheneminen ja anhedonia, energiatasot/väsymys, uni, itsesyytöksen tunteet, itsetunto, keskittymiskyky, ruokahalun ja painon muutokset, psykomotoristen muutosten arviointi, ITSETUHOISUUS? Tukena esim. PHQ9, MÅDRS, BDI-21 yms. </li>
  <ul>
    <li>Masennus voi hyvinkin aiheuttaa uniongelmia ja keskittymisvaikeuksia</li>
    <li>ADHD-potilailla yleisimmät psykiatriset komorbiditeetit ovat masennus, bipolaari, ahdistus ja päihdehäiriöt</li>
    <li>Samalla mahdollisesti arvio, voisiko olla hypomaniassa nyt (kuitenkin unen tarpeen väheneminen, keskittymisvaikeudet)</li>
  </ul>
<li>Ahdistuksesta ja mahdollisista oireista kysyminen. Tukena esim. OASIS-kysely</li>
  <ul>
    <li>Ahdistus voi hyvinkin aiheuttaa uniongelmia ja keskittymisvaikeuksia</li>
  </ul>
<li>Päihteiden käytön kartoittaminen: alkoholi, tupakka, kannabis, muut päihteet?</li>
  <ul>
    <li>Tarvittaessa tarkemmat labrat, kuten PEth ja U-Huum</li>
    <li>Päihteet voivat hyvinkin olla keskittymisvaikeuksien ja uniongelmien taustalla; käyttö vaikuttaa myös ADHD-lääkityksen mahdollisuuteen ja valintaan</li>
  </ul>
<li>Psykoottisia oireita?</li>
  <ul>
    <li>Keskittymisvaikeudet</li>
  </ul>
<li>Jos ADHD-lääkitystä ajateltaisiin, niin EKG, verenpaine ja syke, tarkempi kardiovaskulaarihistoria - stimulanttilääkityksen suhteen tärkeää</li>
<li>Miten käyttää sosiaalista mediaa ja muutenkin älylaitteita? Miten syö? - Molemmat tärkeitä unen ja keskittymisen kannalta</li>
<li>Erityisesti ADHD-selvittelyinä: ONKO OLLUT JO ALLE 12-VUOTIAANA KESKITTYMISVAIKEUKSIA TAI YLIAKTIIVISUUS/IMPULSIIVISUUSOIREITA ja ovatko ne jatkuneet nyt aikuisuuteen saakka (oirekuvassa voi kyllä ollut tapahtunut muutoksia)? *INFORMANTTIEN JA TODISTUSTEN HYÖDYNTÄMINEN TÄSSÄ myöhemmin. Onko ADHD-selvittelyitä koskaan ollut lapsuudessa? Missä yhteyksissä oireet ilmenevät (ovatko vain hakemuksia tehdessä vai ilmenevätkö vähintään 2 tilanteessa, kuten kavereiden kanssa jutellessa koulussa ja myös kotona)? Miten oireet häiritsevät tarkemmin? Kuinka kauan oireet ovat nyt kestäneet häiritsevinä? Onko perheessä ADHD? Tarkempi oirekuva esim. DIVA-5:n mukaan, jos kuvautuu potentiaalisena ADHD:na. DIVA-5 voidaan toteuttaaa myöhemmilläkin vastaanotoilla tai niitä ennen hoitajan toimesta, jos koetaan se tarpeelliseksi (esim. tila kuvautuu vahvasti ADHD:na ja tällä vastaanotolla annetut elintapaohjeet eivät tuota tulosta). Siinä kysellään DSM-5:n mukaan tyypilliset oireet.</li>
  <ul>
    <li>Keskittymispuutosoireet: Huolimattomia virheitä? Keskittymiskyvyn puutosta? Vaikeuksia kuunnella toisia? Kadottaa tavaroita? Ei saata tehtäviä päätökseen? Vaikeuksia järjestellä elämää ja tehtäviä? Ei halua aloittaa haastavia tehtäviä? Unohtelee rutiinijuttuja? Helposti häiriintyy ulkoisten ärsykkeiden seurauksena? </li>
    <li>Impulsiivisuus/yliaktiivisuus: Juoksentelee ympäriinsä? Vaikea leikkiä hiljaa (varsinkin lapsilla, aikuisilla muissa toimissa)? Ei kestä jonotusta? On kuin kone päällä koko ajan? Räplää tai fidgetoi koko ajan? Huutelee vastauksia ennenaikaisesti? Ei jaksa istua paikallaan? Puhuu paljon? Puhuu toisten päälle?</li>
  </ul>

  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="c"
          data-hide-label="c - Piilota vastaus">
    c
  </button>
  <div class="solution-content">

ADHD:n tutkimusprosessi on yleensä suhteellisen pitkäkestoinen. Aluksi (kuten nyt tällä vastaanotolla) selvitellään yleisesti tilannetta ja arvioidaan mahdollisia muita taustalla olevia asioita. Annetaan usein sopivia ohjeita, joilla korjata mahdollisia taustalla olevia elintapaongelmia ja otetaan myös muut mielenterveysasiat hoitoon, jos niitä ilmenee (esim. masennus; ei kuitenkaan heti masennuksen tai ahdistuksen lääkehoidon aloitusta ilman ESH-konsultaatiota, koska potilaalla mm. bipolaari). 

Myöhemmin jos tila ei oikein helpota, niin sitten ADHD:n tarkempi selvittely, esim. DIVA-5, informanttien käyttö lapsuuden suhteen (myös potilas itse voi kertoa lapsuudestaan ja tuoda todistuksia, jos vain ei mitenkään saada informanttia käyttöön) ja sitten mahdollisesti tarpeen mukaan lääkityksen aloittaminen, jos koetaan, että oirekuva on sen verran vakava ja potilas haluaisi hoitoa. 

Perusselvittelyt tehdään tietysti PTH:ssa ja usein myös tarkemmatkin selvittelyt. PTH:ssa tulee kuitenkin aina olla mahdollisuus konsultoida psykiatria eikä diagnoosia ja lääkitystä aloiteta ilman konsultaatiota. Vaikeammissa ns. komplisoituneissa tilanteissa (paljon komorbiditeetteja), hoidetaan selvittelyt ja hoidon aloitus pääsääntöisesti ESH:ssa. Potilaan aikaisempi historia huomioiden soveltuu hän todennäköisesti paremmin ESH:n arvioon, jos tila vaikuttaa siltä, että oirekuva sopii ADHD:seen. 

  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="d"
          data-hide-label="d - Piilota vastaus">
    d
  </button>
  <div class="solution-content">

Lääkitystä ei voida nyt heti aloittaa, koska tarkempia selvittelyitä ei ole vielä tehty ja potilas muutenkin todennäköisesti tarvitsee ESH:n arvion. Siellä sitten asetetaan hoitolinjat tarkemmin. Nyt PTH:n tarkoituksena on selvittää oirekuvaa tarkemmin ja mahdollisesti tehdä lähete ESH:hon, jos se koetaan tarpeelliseksi (aka ADHD on todennäköinen ja muut asiat eivät selitä ongelmia). 

Tämä tulee tuoda tietysti rauhallisesti potilaalle esille ja selittää, miksi näin tehdään, jottei potilaasta tunnu, että hänen ongelmiaan ei oteta tosissaan
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="e"
          data-hide-label="e - Piilota vastaus">
    e
  </button>
  <div class="solution-content">

Perusselvittelyt nyt tässä vastaanotolla: uni, masennus/hypomania, ahdistus, päihteet yms. Alustavaa perusselvittelyä ADHD-oireista (esim. onko ollut lapsuudessa) ja niiden perusteella jo mahdollisesti poissulku (esim. ei ole ollut lapsuudessa). Annetaan osuvia ohjeita elintapojen parantamiseen, jos korjattavia kohtia löytyy (unihygienia, päihteet motivoivan haastattelun kautta, älylaitteet, ruokailu). Netistä löytyy myös paljon omahoito-ohjeita. 

ESH-konsultaatio tarkemman anamneesin perusteella (esim. masennus, ahdistus yms. jos on niin miten hoidetaan. Potilaalla bipolaari, niin ei voi vain aloittaa SSRI PTH:ssa). Jos tila vaikuttaa pääasiallisesti ADHD:lta, niin ESH:n konsultaation perusteella lähete sinne. 
  </div>
</div>

### 

Terveyskeskusvastaanotollesi tulee 50-vuotias mies, joka valittaa väsymystä ja ärtyisyyttä. Hänellä ei ole ns. perussairauksia tai lääkityksiä. Hän on normaalipainoinen ja pelaa padelia kaksi kertaa viikossa. Hän työskentelee keskisuuren yrityksen keskijohdossa ja hänellä on vaimo ja kolme lasta. Hän ei mielellään käy lääkärissä ja nytkin hän on tullut terveyskeskukseen, sillä hän ei halua kenenkään firmassa näkevän hänen menevän työterveyshuoltoon. Hän on kuitenkin käynyt oma-aloitteisesti ja omakustanteisesti edeltävästi laajoissa laboratoriokokeissa, eikä näiden tuloksissa ole poikkeavuuksia.

- a. Miten etenet informaation keruussa? Mitä kaikkea kysyt ja tutkit ja miten?
- b. Kun käy ilmi, ettei potilas ole tyytyväinen uneensa, miten kartoitat tätä ongelmaa tarkemmin?
- c. Minkälaista psykoedukaatiota annat potilaalle unettomuuden syistä ja omahoidollisista keinoista?
- d. Diagnoosit ovat lieväasteinen masennus ja ei-elimellinen unettomuus. Kirjoita sairauskertomusmerkintäsi kohta Suunnitelma. Saat itse keksiä, minkälaiset hoitovaihtoehdot tulevat kyseeseen potilaan preferenssien ja käytettävissä olevien palveluiden näkökulmista, mutta perustele.

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

Oireista ja kaikesta muustakin tulee kysyä rauhallisesti ja avoimesti. 

<li>Väsymys: milloin alkanut? onko jatkuvaa? kuinka voimakasta? onko ennen ollut?</li>
<li>Elämä: onko muutoksia tapahtunut? mikä stressaa? mistä saa voimaa?</li>
<li>Hoitohistoria: milloin viimeksi käynyt lääkärissä?</li>
<li>Sukuhistoria: somaattisia/psykiatrisia sairauksia suvussa?</li>
<li>Päihteet: Alkoholi, tupakka, kannabis, muut päihteet?</li>
<li>Uni: Miten nukkuu? Onko tyytyväinen uneensa? Miksi luulee, ettei saa unta?</li>
<li>Somaattinen status: auskultaatio (sydän, keuhkot), turvotukset, verenpaine + syke, palpaatio ympäriinsä, tarvittaessa EKG jos kuvailee aikaisempia rintatuntemuksia tai rytmihäiriötuntemuksia?</li>
<li>Mitä laborissa mitattiin? (onko pvk, tsh, t4v, alat, asat, testo-vl, krea, k, na, ca yms)?</li>
<li>Psykiatriset oireet: mieliala (masennus/hypomania), ahdistuneisuus...?</li>
<li>Itsetuhoisuus</li>

  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

<li>Mitä tarkoittaa, ettei ole tyytyväinen uneensa (avoin kysymys)?</li>
<li>Onko ongelma enemmänkin nukahtamisessa, heräilyssä yöllä vai liian aikaisesta heräämisestä?</li>
<li>STOP-BANGilla uniapnean mahdollisuuden arviointi ja tarvittaessa yöpolygrafialla poissulku</li>
<li>Unihygieniasta (kuinka säännöllinen unirytmi, mitä tekee sängyssä, mitä miettii nukahtaessaan (onko samoja asioita kuin päivällä pyörii päässä), miten juo kahvia/kofeiinia, päihteet, älylaitteet, ulkona liikkuminen (saako valoa silmiinsä), häiritseekö vaimo/lapset jotenkin unta), huoneen lämpötila/pimeysaste)?</li>

  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="c"
          data-hide-label="c - Piilota vastaus">
    c
  </button>
  <div class="solution-content">

Tärkeintä unettomuuden psykoedukaatiossa on kertoa sen yleisyydestä ja ns. de-eskaloida potilaan ajatuksia tilanteesta. Tilapäinen unettomuus kuuluu osaksi normaalia elämää (aka käytännössä kaikki kokevat joskus) ja sen yleisin syy on lisääntynyt stressi elämässä. Pelkästään tämä rauhoittelu voi olla ratkaisevaa joillekin potilaille, koska se voi poistaa katastrofiajattelun kehän, joka on hyvin tärkeä osa unettomuuden kroonistumista (ajatellaan, että tilapäinen unettomuus jää pysyväksi, ei saada enää koskaan unta ja tämä pilaa elämän yms -> nämä ajatukset stressaavat entisestään ja pahentavat unihäiriötä). 

Tärkeää on myös painottaa, että alkoholi tai muut päihteet eivät ole ratkaisu unettomuuteen, niillä ei kannata itsehoitaa ongelmaa. 

Omahoidollisista keinoista voi kertoa mm. erilaisia omahoito-ohjelmia hyödyntämällä.  Kuitenkin yleisesti voi kuvailla hyvän unihygienian piirteitä, kuten säännöllinen unirytmi (vähintäänkin herää aina samaan aikaan, ja myös pääsääntöisesti tulisi mennä samaan aikaan aina nukkumaan), huoneen lämpötila sopivan viileäksi (viileässä nukkuu paremmin yleensä), huoneen pimeydestä huolehtiminen (pimennysverhot), sängyn käyttäminen vain nukkumiseen ja seksiin (ei siis älylaitteiden selaamista sängyssä), liian pitkien päiväunien ja muutenkin vaaka-asennon välttämistä voi suositella, sopivasti urheilua ja oikea ajoitus sille (ei liian rankkaa juuri ennen nukkumaanmenoa, joko aamulla tai sitten viimeistään muutama tunti ennen nukkumaanmenoa), kahvin ja muutenkin kofeiinin välttäminen liian myöhään käytettynä (esim. viimeinen kahvi joskus alkuiltapäivästä), säännöllinen ja itselle sopiva ruokarytmi (jotkut suosittelevat hiilihydraattipitoista iltapalaa, mutta jotkut taas nukkuvat paljon paremmin, jos eivät ole syöneet hetkeen (esim. viimeinen ateria olisi jo iltapäivällä (näin itse teen)), rauhoittuminen/meditaatio ennen nukkumaanmenoa (saadaan ajatukset pois pyörimästä päästä)

Unettomuuden hoidossa ensisijaista on ns. CBT-I (kognitiivinen käyttäytymisterapia unelle), jota voi hyödyntää ilman virallista hoitokontaktiakin esim. sovellusten kautta, jos ei halua hoitajan tai nettiterapian kautta tätä toteuttaa virallisesti kontrolloituna.
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="d"
          data-hide-label="d - Piilota vastaus">
    d
  </button>
  <div class="solution-content">

Suunnitelma: 

Potilaan tila sopii lieväasteiseen masennukseen ja ei-elimelliseen unettomuuteen. Keskusteltu potilaan kanssa lääkehoidon tarpeesta, eikä potilas koe tällä hetkellä ainakaan masennuksen suhteen tarvetta lääkitykselle. Ehdotettu nettiterapiaa ja sitä kautta ohjattua omahoitoa ja tähän suostuu. Käy kontrollikäynneillä muutaman viikon välein psykiatrisella hoitajallamme ja näillä väleillä suorittaa nettiterapiaa. Tarvittaessa sitten ilmoittaa hoitajalle, jos onkin halukas kokeilemaan lääkitystä. 

Unettomuuden suhteen annettu laajasti psykoedukaatio unettomuudesta ja sen omahoidosta ja ohjattu myös mielenterveystalon omahoito-ohjeiden pariin. Keskusteltu lääkehoidon tarpeesta (esim. pieniannoksinen doksepiini), mutta on varovainen unilääkkeiden suhteen, koska monet kavereistaan ovat koukussa niihin. Keskusteltu siitä, että doksepiini ei todennäköisesti koukuttaisi, mutta ei kuitenkaan nyt koe sitä tarpeelliseksi. Ottaa kuitenkin omahoito-ohjeet vastaan mielellään ja myös ajattelee kokeilevansa CBT-I-omahoitoa ilman hoitajan vastaanottoa. Sovittu, että psykiatrisen hoitajan vastaanotolla keskustelee unettomuutensa paranemisesta ja tukikeinojen toimivuudesta lisää ja tarvittaessa ilmoittaa, jos tarvitsee lääkitystä. 
  </div>
</div>


### M1   

Isä tuo 15-vuotiaan nuoren miehen yhteispäivystykseen ja toteaa, että he eivät enää vaimon kanssa tiedä, mitä pojan kanssa tehdä. Isä kertoo pojan olleen vielä seitsemännellä luokalla ”kunnon poika”, mutta kahdeksannen luokan alun jälkeen ”mistään ei ole enää tullut mitään”. Nuori käy tällä hetkellä 9. luokkaa, mutta poissaoloja on niin paljon, että isä epäilee, että nuori ei pääse luokaltaan; ”eihän tämä enää nouse sängystäkään”. Isä kuvaa tuohtuneena, että kaikkea on kokeiltu, mutta kun poikaa ei vain kiinnosta ja kannabiksen käytöstä ja kortitta ajelustakin poika on isän mukaan jäänyt kiinni. Päivystykseen he päättivät lähteä, kun nuori riidan yhteydessä huusi vielä tappavansa vanhempansa ja oli ollut jo juoksemassa kohti keittiön veitsitelinettä, kun isoveli sai hänet pysäytettyä.

 Isän ja pojan välit vaikuttavat sen verran tulehtuneilta, että päätät haastatella nuorta myös ilman isää. Kysyt aluksi nuoren mielialasta ja tämä vastaa: ”No kun mä en vittu enää jaksa. Ei mua kiinnosta, miten mun koulu menee, en mä jaksa mitään kavereita nähä, kaikki on ihan vitun sama”. Itsetuhoiset ajatukset nuori kuitenkin kiistää. Kysyt kotona aiemmin tänään olleesta riidasta ja nuori vastaa: ”Ne on vaan niin saatanan ärsyttäviä. Mua vituttaa niin helvetisti, et mul vaan päässä naksahtaa. En mä tiedä, mitä mä sellasessa tilanteessa vielä joskus teen”.

Haastattelussa nuori on vähäilmeinen ja ärtynyt. Antaa masentuneen ja näköalattoman vaikutelman. Ottaa niukasti katsekontaktia ja istuu koko ajan toppatakki päällä ja pipo silmillä. Toteaa, ettei tarvitse mitään apua, kunhan hänet vain jätetään rauhaan. Vanhemmat toivovat nuorelle apua, eivätkä koe pärjäävänsä tämän kanssa kotona.

Jos M1-lähete on mielestäsi tarpeellinen, täytä liitteenä olevaan M1-lähetteeseen kaikki tarpeelliset tiedot siten, että lähete on juridisesti pätevä ja johdonmukainen.  Jos M1-lähete ei ole mielestäsi tarpeellinen, kuvaa esseevastauksessa tahdosta riippumattoman hoidon kriteerit ja arvioi kriteerien täyttyminen nuoren kohdalla.

[Tyhjä M1-lomake](images/tyhjaM1lomake.pdf)

<div class="">
  <button class="solution-button"
          data-label="Vastaus"
          data-hide-label="Piilota vastaus">
    Vastaus
  </button>
  <div class="solution-content">

[M1-lähete](images/tarkkailulahete_1.pdf)

  </div>
</div>
