# 2021

## Tentistä {#Tentista}

Wikistä löytyy mallivastaukset, joita olen hyödyntänyt näissä vastauksissa. Ne ovat usein kuitenkin liian lyhyesti kirjoitettuja ja ovat paikoittain epäselviä, joten olen muokannut niitä tarpeen mukaan. 

### Uniongelmia keski-ikäisellä naisella

Pidät terveyskeskuksessa tavanomaista vastaanottopäivää. Potilaaksesi tulee  53 v. nainen, joka on aiemmin somaattisesti terve lukuun ottamatta ajoittain rekisteröityjä korkeita verenpainearvoja. Painoindeksi 20. Potilas asuu yksin, lemmikkikissa on ollut jo 15 vuotta.  Potilas on työskennellyt jo yli 12 vuotta keskisuuressa yrityksessä IT-järjestelmäosaajana.

Vastaanotolle tulemisen syyn kertoo, että muutaman kuukauden ajan on ollut uniongelmia ja ajoittaisia voimakkaitakin alaselkään sijoittuvia kipuja, nukkuminen tuntuu jotenkin tuskaiselta. Kipuja on yrittänyt  lievittää Ibuprofeenilla ja luontaistuotteilla ilman selkeää apua. Kertoo myös töissä käymisen muuttuneen vastenmieliseksi ja töihin lähtö aamulla tuntuu hankalalta. Töissä silti pystyy käymään. Käynnin edetessä potilas kertoo, että työyhteisössä on tapahtunut neljä kuukautta sitten organisaatiomuutos ja työympäristö on muuttunut ja osin  työkaveritkin vaihtuneet. Potilas on vastaanotolla varautuneen oloinen ja tuijottaa sinua ajoittain pistävän oloisesti. Lopulta hän kertoo, että edellä mainitussa työpaikan muutoksessa ja tietojärjestelmien vaihtumisen yhteydessä  hänen henkilökohtaisia intiimejä tietojaan olisi tarkoituksella laitettu nettiin. Tämä ajatus pyörii mielessä koko ajan. Kokee, että töissä useimmat tietävät nyt hänen asiansa ja katsovat potilasta eri tavalla kuin ennen.

- a. Miten lähdet selvittämään asiaa? Pohdi erilaisia diagnostisia ja erotusdiagnostisia vaihtoehtoja. 
- b. Kuvaa toimintasuunnitelmasi tilanteessa, jossa potilas kertoo olevansa halukas saamaan apua ja vaivojensa jatkotutkimuksiin, mutta suhtautuu hyvin epäilevästi työpaikan asioiden selvittelyyn.

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

Aluksi selkäoireiston tutkiminen: onko cauda-oireita, kuinka nopeasti kehittynyt, onko säteilevää kipua, traumaa selkään, aikaisempia operaatioita, infektio-oireita? Sensoriikka? Lasegue? Lihasvoimat? 

**Sitten uniongelman tarkempi selvittely: onko enemmänkin vaikeuksia nukahtamisessa, yönaikaisessa heräilyssä vai herääkö liian aikaisin?**

<li>Onko uniapneaan viittaavaa (eim. puoliso maininnut hengityskatkoksista)</li>
<li>Onko levottomien jalkojen tunteita?</li>
<li>Kuinka paljon arvioi saamansa unta?</li>
<li>Unihygienia (kahvi, älylaitteet sängyssä, päiväunet, päiväväsymys, valon saaminen silmiin, huoneen lämpötila, huoneen pimeys, viettääkö aikaa sängyssä päivisin)</li>

**Yleisselvittelyt:**

<li>Psykiatrinen historia, aiempia hoitoja? Oirekyselyt masennuksesta, ahdistuneisuudesta, bipolaarisuudesta.</li>
<li>Aiemmat ja akuutit ympäristön kuormittavat tekijät (työpaikka-asia tarjoutuu selkeästi sellaiseksi, mutta voi olla muutakin). Tarkemmin selvittely siitä, voiko tietojen vuotaminen nettiin olla todellista?</li>
<li>Yleisesti miten selittää työasioita / asioita yleisesti; kuvautuuko psykoottista?</li>
<li>Menopaussioireet?</li>
<li>Päihdeanamneesi</li>
<li>Mitä "luontaistuotteita" käyttää; näistä valistaminen</li>
<li>Sukuhistoria</li>
<li>Neurologinen status ja orientaation arvioiminen</li>
<li>Orgaaniset syyt (TSH, T4v, PVK, gluk, B12, B9, D-vit, CRP, K, Na, Krea, ALAT, mahdollisesti MRI-mahdollisuudesta konsultoiminen muistin kuvautumisen ja neurologisen statuksen perusteella)</li>
<li>Potilaan painoindeksi on myös kohtalaisen alhainen tämän ikäiselle. Miten paino on kehittynyt viime aikoina?</li>
<li>Muita informaatiolähteitä, esim. läheisiä kannattaa mahdollisuuksien mukaan haastatella, jos potilas antaa siihen luvan</li>


Diagnostisia vaihtoehtoja on useita ja potilaalla voi hyvinkin olla useita häiriöitä:

<li>Psykiatrinen:</li>
  <ul>
   <li>Unihäiriö on ilmeinen, potilas tuottaa myös depressio-oireita, mielialahäiriö (unipolaaridepressio, psykoottinen masennus, bipolaarisuudesta ei tässä näyttöä) + ahdistuneisuushäiriö hyvinkin mahdollisia</li>
   <li>Potilas tuottaa mielialan mukaisia todennäköisiä psykoosioireita eli psykoosisairaus on mahdollinen (harhaluuloisuushäiriö tai jopa skitsofrenia voi tulla kyseeseen vaikka skitsofrenia yleensä puhkeaa aiemmin). Psykoosioireista tuleekin kysellä tarkemmin eli miten potilas töissä tapahtuneen selittää.</li>
 </ul>

<li>Selkäkivut:</li>
  <ul>
   <li>Selvittelyiden jäädessä negatiivisiksi on vain epämääräistä alaselkäkipua. Ensisijaisesti mobilisaatio/fysioterapia/työergonomian parantaminen ja tulehduskipulääkkeet/parasetamoli.</li>
   <li>Psykiatrinen puoli todennäköisesti pahentaa oireilua.</li>
   <li>Jos oireet eivät mitenkään lähde paranemaan, niin ehkä MRI-harkinta</li>
 </ul>
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

Alkuselvittelyjä voi yhteistyö-ja toimintakykyiselle potilaalle tehdä myös perusterveydenhuollon tasolla (toki paikalliset olosuhteet vaikuttavat selvittelyjen ja hoidon porrastukseen). Konsultoi psykiatria herkästi muutenkin tällaisessa tilanteessa, puhelimitsekin voi hyvin onnistua, aina ei tarvitse lähettää potilasta eteenpäin. Koko problematiikan selvittely ei onnistu yhden käynnin aikana. Potilas vaikuttaa pääosin yhteistyökykyiseltä, joten ohjelmoidaan alkuun statuksen mukaiset laboratoriotutkimukset (mm. peruslabrat, La, CRP, elektrolyytit, TSH, maksa-ja munuaisten toiminta, gluk, D-vitamiini).

Selkäongelmien hoidossa ensisijaisesti mobilisaatio/fysioterapia/työergonomian parantaminen ja tulehduskipulääkkeet/parasetamoli. 

Unettomuuden hoidossa pyritään ensin käyttämään ei-lääkkeellisiä keinoja (unihygienian ohjaus ja elintapojen korjaus). Tarvittaessa jokin unilääke lyhytaikaisesti; esim. pieniannoksinen doksepiini / z-lääke, kuten tsopikloni 7,5 mg , 1 tabl tarv. yöksi / pieni annos ketiapiinia (esim. 25 mg; voisi olla muutenkin hyvä ajatellen psykoosin suuntaan viittaavaa oireilua, vaikka näin pieni annos ei olekaan antipsykoottinen). 

Kontakti potilaaseen on ehdottomasti syytä säilyttää (uusi käynti esim. 2-3 viikkoa tai ainakin puhelinkontakti lab tulostenkin suhteen). Tulee myös selvittää, onko työterveyspalveluja saatavilla? Työolosuhteiden tarkastelu on hyvinkin tarpeen, koska ne näyttävät tässä olevan osallisina. Jos psykiatrinen sairaanhoitaja on saatavilla potilas voisi purkaa huolia siellä mikäli potilas kokee sen mahdolliseksi. Lyhyt sairasloma voi olla tarpeen, tästä tulee keskustella potilaan kanssa.

Masennuksen hoito: lievää/keskivaikeaa voi hoitaa terveyskeskuksessa käypä hoito prinsiippien mukaisesti. Lääkehoitoa voi harkita aloitettavaksi jo suoraankin, mutta selvittelyä on hyvä tehdä ensin. Tähän vaikuttaa myös se, että onko potilaalla itsetuhoajatuksia/suunnitelmia? Psykoosioireen lääkehoito on niin ikään tässä mahdollinen, esim. ketiapiini alkuun; kuitenkin ESH:n konsultaation perusteella. Psykoosioireilun suhteen tilanne voi eskaloitua ja silloin lähetetään psykiatriseen erikoissairaanhoitoon. M1 lähete ei näillä tiedoilla ole tarpeellinen, mutta voi sellaiseksi muuttua, jos tilanne seurannassa pahenee.
  </div>
</div>

### Paniikkihäiriö

Toimit tk-lääkärinä ja vastaanotollesi tulee 35-vuotias toimistotyötä tekevä nainen, jolla on vuoden ajan ollut paniikkikohtauksia ja parin viimeisen kuukauden aikana niitä oli tullut päivittäin. Paniikkioireilu oli alkanut veljen kuoltua syöpään. Potilaan mies jäi työttömäksi kolme kuukautta sitten. Potilaalla itsellään on ollut runsaasti työpaineita viime aikoina. Potilas on lehdestä lukenut paniikkihäiriöstä ja arvelee, että siitä voisi olla kysymys, vaikka onkin vaikea hyväksyä sitä, että itsellä olisi jokin psyykkinen häiriö. Lopulta potilas oli päättänyt tulla lääkärin vastaanotolle, kun ei enää pystynyt lähtemään töihin paniikkikohtauksen pelon takia. Aiempaa psykiatrista anamneesia ei ole.

Teet paniikkihäiriön diagnoosin, joka tuntuu potilaastakin oikealta diagnoosilta. Ennen kuin ehdit aloittaa hoidosta keskustelemista, potilas sanoo, että ei halua aloittaa psyykelääkitystä.

Miten toimit?

<div class="">
  <button class="solution-button"
          data-label="Vastaus"
          data-hide-label="Piilota vastaus">
    Vastaus
  </button>
  <div class="solution-content">

Luottamuksellisen lääkäri-potilassuhteen luominen ja ylläpitäminen kaiken a ja o. Älä lähde syyttämään tai painostamaan, kysele avoimesti ja anna potilaan selittää asiat rauhassa. 

<li>Kysy ensin, miksi hän ei ole halukas käyttämään psyykelääkkeitä</li>
  <ul>
   <li>Jos potilas ei oikein osaa vastata, voidaan normalisoida potilaan tunteita kertomalla, että monet ihmiset vierastavat näitä lääkkeitä sivuvaikutusten, riippuvuuden tai leimautumisen pelon takia tai voivat pelätä sitä, että lääkkeen käyttö näkyy päälle</li>
   <li>Kaiken kaikkiaan potilaan negatiivista suhtautumista lääkkeisiin pidetään normaalina asiana</li>
 </ul>
<li>Anna psykoedukaatiota paniikkihäiriöstä, sen hoidosta ja psyykelääkkeistä yleisesti. </li>

Motivoivan haastattelun kautta sitten yritetään saada potilas oivaltamaan lääkkeiden tarpeellisuus

<li>Periaatteita mm. empatia, ristiriidan havaitseminen (toivomusten ja käytöksen välillä), väittelyn vältteleminen, vastarinnan myötäily, pystyvyyden tunteen tukeminen</li>
<li>Keskustelu on siis yhteistyötä potilaan kanssa ja potilas päättää lopulta itse hoidostaan (autonomia)</li>

Jos potilaasta tuntuu vaikealta päättää, niin voi sanoa, että päätöstä ei tarvitse tehdä heti; potilas voi hoitosuhteen myötä myöhemmin motivoitua lääkkeen käyttöön. Tuodaan esille myös muita hoitovaihtoehtoja: 

<li>Potilaalle kerrotaan psykoterapiasta ja muusta psykososiaalisesta hoidosta.</li>
<li>Voidaan ohjata psykiatriselle hoitajalle tai tk-psykologille</li>
<li>Omalla vastaanotolla voi jatkaa tk-lääkärin "psykoterapiaa" omien taitojen mukaan; voi esim. vinkata hengitys- ja rentoutusharjoituksia tai mindfulness-harjoituksia</li>
<li>Nettiterapia vaihtoehtona (HUS-mielenterveystalo)</li>
<li>Yksityssektorikin auki, potilas voi halutessaan käyttää niiden palveluita</li>
<li>Jos hoito ei oikein etene, niin lähettäminen psykiatriseen erikoissairaanhoitoon terapia-arvioon</li>

Tarvittaessa lyhyen sairausloman kirjoittaminen ja yhteys työterveyshuoltoon: järjestelyt työpaikalla kuormituksen keventämiseksi. 

Kaiken tämän lisäksi on myös tärkeää selvittää komorbiditeetit ja mahdollisesti tarjota hoitoa niihinkin. 
  </div>
</div>

### Nukkumisvaikeuksia depressiopotilaalla

Kyseessä on 36-vuotias nainen. Hän on avioliitossa, kahden teini-ikäisen lapsen äiti ja koulutukseltaan ekonomi. Hän työskentelee pankissa keskiasteen johtotehtävissä. Oman äitinsä kuoleman jälkeen noin kaksi vuotta sitten hän sairastui depressioon. Äiti sairasti rintasyöpää ja kuolema oli ennakoitavissa jo pitkään.

Työterveyslääkäri on kirjoittanut hänelle tähän mennessä hoidoksi kahta eri masennuslääkettä (essitalopraami ja duloksetiini), joita hän on käyttänyt järkevillä annoksilla vuorotellen nyt yli vuoden ajan. Hänen oireensa ovat lievittyneet ja hän on voinut palata takaisin työelämään puolen vuoden sairausloman jälkeen, mutta kunnolla hän ei ole toipunut.

Hänellä on edelleen nukkumisvaikeuksia (erityisesti aamuyön heräämisiä), aloitekyvyttömyyttä, mielialojen vaihtelua ja muistivaikeuksia. Hän edelleen pohtii olisiko voinut tehdä jotakin äitinsä hyväksi ennen tämän kuolemaa ja kokee siitä syyllisyyttä.

Mitä vaihtoehtoja potilaan toipumisen edistämiseen on käytettävissä?


<div class="">
  <button class="solution-button"
          data-label="Vastaus"
          data-hide-label="Piilota vastaus">
    Vastaus
  </button>
  <div class="solution-content">

Kyseessä on tilanne, jossa potilaan masennus on pitkittynyt kesken jääneen tai komplisoituneen surutyön takia. Tutkimuksessa tulisi tarkemmin selvittää minkälainen suhde potilaalla oli äitiinsä. 

Hoitoon pitäisi kombinoida psykososiaalisia elementtejä, jotka edesauttaisivat surutyön etenemistä. Tähän tarkoitukseen sopivat monet lyhytpsykoterapiat, mutta erityisen hyvin interpersonaalinen psykoterapia (IPT). Myös terveyskeskuslääkäri voi tavallista pitempien vastaanottokäyntien puitteissa edistää menetyksen psykologista työstämistä keskustelemalla potilaan kanssa äitiä kohtaan tuntemistaan tunteista. On tärkeää, että potilas voi luottamuksellisen hoitosuhteen turvin ilmaista myös ristiriitaisiakin tunteita menetettyä äitiä kohtaan.
  </div>
</div>

### Kouluterveydenhoittaja saattaa tytön vastaanotolle

Työskentelet terveyskeskuksessa ja osana työnkuvaasi toimit myös koululääkärinä läheisellä yläasteella. Kouluterveydenhoitaja soitti sinulle hetkeä aiemmin ja lähti saattamaan 15-vuotiasta tyttöä vastaanotollesi. Hän ehti lyhyesti kertomaan, että hän on tavannut nuorta nyt keväällä pariin otteeseen mielialaoireiden vuoksi. Nuoren opettaja oli huolestunut hänestä, kun nuori oli muuttunut aiempaa hiljaisemmaksi ja alakuloisemmaksi. Wilmaan oli myös alkuvuoden aikana kertynyt jonkin verran aamumyöhästelyjä ja koko päivän poissaoloja, joille nuori ei antanut selitystä. Nuori on käynneillä kuvannut vanhempiensa välit riitaisiksi ja myös nuoren pikkusiskon reumasairaus aiheuttaa kuormitusta perheessä. Tämänpäiväisellä käynnillä kouluterveydenhoitajan vastaanotolla kävi esille, että nuorella on itsetuhoisia ajatuksia ja hän on viillellyt toistuvasti. Pyytäessä nuori oli näyttänytkin terveydenhoitajalle käsivarressaan olevaa tuoretta haavaa. Terveydenhoitaja oli huolestunut kovasti nuoren tilanteesta ja varasit ystävällisesti hänelle kalenteristasi juuri peruuntuneen ajan.

Vastaanotollesi saapuu tavanomaiseen tapaan pukeutunut ulkoisesti ikäisensä oloinen tyttö. Hän istuu pääasiassa katse maahan luotuna, mutta ottaa aika ajoin rohkeammin katsekontaktia. Hän vastaa kysymyksiisi, mutta on vastauksissaan lyhytsanainen ja välillä hieman ärtynytkin. Kysyt häneltä asiasta ja hän kertoo olevansa turhautunut vastaamaan aina samoihin kysymyksiin. Kotitilanteen suhteen nuori kuvaa, että hänen vanhempansa ovat eroamassa ja ovat talvesta lähtien riidelleet usein kovaäänisesti. Väkivallasta nuori ei tiedä, mutta on joskus kuullut tavaroiden rikkoutumista ja kertoo äitinsä itkevän usein. Riitatilanteissa vetäytyvät siskonsa kanssa yleensä omiin huoneisiinsa eikä osaa sanoa, mitä sisko ajattelee tilanteesta. Kertoo vointinsa olleen huonompi jo viime syksystä lähtien, mutta kotitilanteen vaikeuduttua kokee vointinsa jollain tavoin notkahtaneen. Nuori kyyneltyy kertoessaan olevansa umpikujassa eikä usko pystyvänsä menemään kotiin.

- a. Pohdi, miten etenet tilanteessa. Mitä arviossasi on tärkeää selvittää, jotta saat tehtyä asianmukaisen jatkosuunnitelman?
- b. Onko tarkkailulähetteen tekeminen mielestäsi vaihtoehto? Arvioi tahdosta riippumattoman hoidon kriteerien täyttymistä kuvauksen sekä kohdassa 1 huomioimiesi asioiden perusteella.
- c. Pohdi, muuttuuko tilanne tahdosta riippumattoman hoidon kriteerien suhteen, jos potilas onkin 18-vuotias?

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

Kuvauksen perusteella potilaan oirekuva viittaa ensisijaisesti depressioon ja itsetuhoisuuteen, mikä tulisi huomioida esitietoja ja statusta arvioidessa. Olennaisinta tässä on keskeisten selvitettävien asioiden tunnistaminen sekä johdonmukaisuus, vaikka johtopäätös työdiagnoosista olisi jotain muuta. Kyseessä on kiireellinen tilanne, joten fokus tulee olla olennaisten asioiden selvittämisessä ja toimenpiteiden suunnittelussa.

<li>Keskeisintä jatkosuunnitelman kannalta on selvittää itsetuhoisuuden vaikeusaste ja mahdollinen itsemurhariski</li>
  <ul>
   <li>Jatkosuunnitelman arviointi perustuu johdonmukaisuuteen. Esimerkiksi jos nuoren itsetuhoisuus on kohtuullisen lievää eikä akuuttia itsemurhavaaraa vaikuta olevan, saattaa vähimmillään riittää tilanteen rauhoittaminen, nuorisopsykiatriseen erikoissairaanhoitoon lähettämisen tarpeellisuuden arviointi, **lastensuojeluilmoituksen teko** ja sen selvittäminen, voiko nuori mennä kotiin vai ei</li>
   <li>Kouluterveydenhoitaja voi myös ottaa yhteyttä vanhempiin tai sosiaalipäivystäjän apuun tukeutua, jos nuori kieltäytyy menemästä kotiin tai kotitilanne ei arviossa kuvaudu turvallisena. Kiireellinenkin sijoitus on yksi mahdollisuus.</li>
   <li>Jos arvion perusteella itsemurhariski on korkea, on nuori syytä ohjata päivystyksellisesti (nuoriso)psykiatrin arvioon ja harkita osastohoidon tarpeellisuutta. Ensisijaisesti tämä tapahtuu kuitenkin vapaaehtoisesti. Lastensuojeluilmoitus tulee aina siinä tapauksessa, kun nuori ohjataan päivystyksellisesti (nuoriso)psykiatrin arvioon.</li>
 </ul>
<li>Myös depressio-oireet kokonaisuudessaan ovat huomionarvoisia: ICD-10-kriteerien täyttyminen ja niiden vaikeusaste. Muutenkin psykiatrinen anamneesi ja komorbiditeetit.</li>
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

Potilas on alaikäinen, joten pitää soveltaa alaikäisten tahdosta riippumattoman hoidon kriteerejä: 

<li>Kaikki seuraavat kolme ehtoa täyttyvät samanaikaisesti:</li>
  <ul>
    <li>Hänellä on vakava mielenterveyden häiriö tai mielisairaus</li>
    <li>Hän on hoidon tarpeessa vakavan mielenterveyden häiriön tai mielisairauden vuoksi siten, että hoitoon toimittamatta jättäminen olennaisesti pahentaisi hänen sairauttaan tai vakavasti vaarantaisi hänen terveyttään tai turvallisuuttaan tai vakavasti vaarantaisi muiden henkilöiden terveyttä tai turvallisuutta</li>
    <li>Mitkään muut mielenterveyspalvelujen vaihtoehdot eivät sovellu käytettäviksi</li>
  </ul>

Lääketieteellisesti mielisairaudella tarkoitetaan sellaista vakavaa mielenterveyden häiriötä, johon liittyy selvä todellisuudentajun häiriintyminen ja jota voidaan pitää psykoosina. Nykyisen tautiluokituksen mukaan tällaisena tilana voidaan pitää deliriumtiloja, skitsofrenian eri muotoja, elimellisiä ja muita harhaluuloisuustiloja, psykoottisia masennustiloja, kaksisuuntaisia mielialahäiriöitä, muistisairauksien vaikea-asteisia ilmenemismuotoja sekä muita psykooseja kuten orgaaniset psykoosit ja päihteiden käytön aiheuttamat psykoottiset tilat. 

Alaikäisellä riittää myös kuitenkin vakava mielenterveyden häiriö. Nyrkkisääntö: Voi olla lähes mikä tahansa mielenterveyden häiriö, joka olennaisesti vaarantaa nuoruusiän kehityksen ja/tai aiheuttaa merkittävän toimintakyvyn aleneman. Kannattaa myös huomioida, että akuutit psykoottistasoiset oireet tulkitaan alaikäisellä käytännössä aina vakavaksi mielenterveyden häiriöksi -> vaikka alaikäinen potilas olisi psykoottinen, hänellä voi aina käyttää perusteena vakavaa mielenterveyden häiriöitä (eikä mielisairautta).

---

Kuvauksen perusteella keskeisin epäiltävä alaikäisen vakava mielenterveyden häiriö on tässä depressio ja itsetuhoisuus, mutta muutkin johdonmukaiset vaihtoehdot käyvät (esim. masennus ja voimakas toimintakyvyn lasku).

Hoidon tarve on perusteltavissa tekstissä kuvatulla voinnin heikkenemisellä hoitoon tuloa edeltävästi sekä potilaan turvallisuuden vaarantumisella.

Viimeinen kriteeri on palveluiden soveltumattomuus. Potilaan hoitokielteisyys tulisi olla hyvin perusteltu, sillä muita mielenterveyspalveluita ei tapauksessa ole toistaiseksi edes kokeiltu eikä tehtävänannossa anneta tästä viitteitä. Potilaalle tulisi ehdottaa hoitovaihtoehtoina polikliinisen hoidon ohella myös vapaaehtoista osastohoitoa. Jos näistä kieltäydytään, niin kriteeri täyttyy. 
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="c"
          data-hide-label="c - Piilota vastaus">
    c
  </button>
  <div class="solution-content">

Tilanne muuttuu sillä tavoin, että depressio ja siihen liittyvä itsetuhoisuus eivät täytä mielisairauden kriteereitä (täysi-ikäisellä vaatimus tulee olla mielisairaus eli psykoottistasoinen sairaus, kun lapsella riittää vakava mielenterveyden häiriö). Tämä voi täyttyä ainoastaan siinä tapauksessa, että on hyvin johdonmukaisesti perusteltavissa löydökset, joilla epäily esim. psykoottistasoisesta masennuksesta (aistiharhoja ei sinänsä tarvitse olla, viitteinä voi esim. olla vakava itsemurhavaara, korostuneen epärealistinen syyllisyys ja syvä toivottomuus) voisi olla asianmukainen.

Toisen kriteerin voi perustella täyttyvän samalla tavoin kuin edellä.

Kolmas kriteeri eli muiden mielenterveyspalveluiden soveltumattomuus täyttyy samalla tavalla eli kysytään vapaaehtoisesta hoidosta. Aikuisilla mahdollisena kriteerinä on myös se, että palvelut voivat olla riittämättömät (paikalliset palvelut riittämättömät; lapsilla ei saa tätä syytä käyttää, koska perustuslain mukaan lapsilla tulisi olla riittävät palvelut käytössään). 
  </div>
</div>

### Testosteronikorvaushoitoa pyytävä mies

Terveyskeskusvastaanotollesi tulee 48-vuotias mies, joka valittaa väsymystä ja ärtyisyyttä. Hänellä ei ole ns. perussairauksia tai lääkityksiä. Hän on normaalipainoinen ja pelaa sulkapalloa kaksi kertaa viikossa. Hän työskentelee keskisuuren yrityksen keskijohdossa ja hänellä on vaimo ja kaksi lasta. Hän ei mielellään käy lääkärissä ja nytkin hän on tullut terveyskeskukseen, sillä ei halua kenenkään firmassa näkevän hänen menevän työterveyshuoltoon. Hän on kuitenkin käynyt oma-aloitteisesti ja omakustanteisesti edeltävästi Puhti-labroissa (www.puhti.fi), joihin asiakas voi varata ajan ilman lääkärin lähetettä. Hänestä on otettu testipaketti nimeltä ”Laaja Puhti-terveystarkastus (mies)”. Muut laboratoriotulokset ovat viitearvoissa, mutta vapaasti laskettu testosteroni on hieman viitearvojen alapuolella. Potilas pohtii voisiko matalakanttisella testosteroniarvolla olla osuutta oireiluun ja hän toivoisi mahdollisimman lyhyttä vastaanottoa ja kokeiltavan testosteronikorvaushoitoa. Seksuaalitoiminnoissa hän ei ole huomannut ongelmia, minkä hän tuo spontaanisti esille.

- a. Miten etenet informaation keruussa? Mitä kaikkea kysyt ja tutkit ja miten?
- b. Kun käy ilmi, ettei potilas ole tyytyväinen uneensa, miten kartoitat tätä ongelmaa tarkemmin?
- c. Minkälaista psykoedukaatiota annat potilaalle unettomuuden syistä ja omahoidollisista keinoista? Kerro myös millä tavalla (vuorovaikutuksen näkökulmasta) käyt tätä keskustelua potilaan kanssa, joka olisi toivonut testosteronista avun ”kaikkiin ongelmiinsa”.
- d. Diagnoosisi on F51, ei-elimellinen unettomuus. Minkälaisen sairauskertomusmerkinnän (sis. Suunnitelma) laatisit? Saat itse keksiä statuslöydöksiä, saat itse kuvata potilaan suhtautumiseen liittyviä asioita, jne.

Ohjeita: Älä kopipeistaa. Sovella oppimaasi ja löytämääsi tietoa. Vastauksesi saavat olla pitkiä, mutta arvostelu perustuu tiettyjen ydinasioiden löytymiseen tekstistäsi. Mahdollisessa rajatapauksessa eduksesi katsotaan, jos sairauskertomustekstissäsi on kohdassa Suunnitelma kuvattu se, miten potilas vielä lähtiessään kysyy testosteroniasioista, ja miten reagoit.

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

<li>Alkuun laajasti ja avoimesti siitä, miksi potilas on hakeutunut vastaanotolle, potilaan omia termejä käyttäen avoimista suljetumpiin kysymyksiin. Kun ongelma tarkentuu, niin kysellään mm. milloin oireilu alkanut, onko jatkunut samanlaisena vai muuttunut, onko löytynyt provosoivia tai helpottavia tekijöitä, ym.</li>
<li>Koska tulosyy on väsymys ja ärtyneisyys, näihin liittyen masennusoireiden kartoitusta; bipolaarihäiriön (ärtyneisyys) poissulkua; elintavoista (liikunta, päihteet ym.); ajankohtaisesta kuormitustilanteesta ja toisaalta voimavaroista; miten yo. oireet vaikuttavat toimintakykyyn (-> mm. onko työterveys tai ajoterveys uhattuna)</li>
<li>Unesta tarkasti; miten nukkuu, uniapneaan viittaavaa...</li>
<li>Jos todella torjuva, avointa pohdintaa siitä miksi lääkäriin tulo oli niin vastenmielistä (ahdistus, mahd. pelot, persoonallisuuspiirteitä tulee samalla kartoitettua).</li>
<li>Lääkityksestä kysyminen. Vaikkei ole säännöllisiä lääkityksiä, onko jotain ns. satunnaisessa käytössä tai luontaistuotteita tai käsikauppavalmisteita, joita ei koe lääkityksiksi</li>
<li>Jos testosteroni keskustelussa isossa roolissa, tarkempi seksuaaliterveyden kartoitus ja tarvittaessa myös oikeaan testosteronivajeeseen liittyvistä oireista kysely (vuorovaikutuksellisesti tärkeää että nämä on käyty läpi, jottei potilas jumiutuisi asiaan). Kiinnostunut ja rauhallinen ote, samalla tehdään selväksi, että asiaa ei kartoiteta tai korjata hetkessä. </li>
<li>Somaattinen ja psykiatrinen status soveltuvilta osin, konetutkimuksia tarvittaessa anamneesin ja statuksen pohjalta.</li>
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

<li>Mitä potilas tarkoittaa, kun sanoo että on tyytymätön uneensa? Siis hyvin avoin kysymys alkuun ja potilaalle tilaa kertoa, potilaan omien termien käyttäminen ja ”ymmärsinkö oikein, että…”</li>
<li>Tarkempi kartoitus: nukahtamisvaikeus, unessa pysymisen vaikeus, heräilyongelma, liian varhainen herääminen aamulla, vai riittävän kestoinen mutta virkistämätön uni? Liikaunisuus? Levottomat jalat? Painajaiset? Kuorsaus, muita viitteitä uniapneasta (aamupäänsärky, mikroheräämisiä paljon, kuinka monta kertaa yössä käy vessassa, onko suu aamuisin kuiva, jne.)</li>
<li>Kuinka paljon saa yössä keskimäärin unta vs. minkä kokee olevan itselleen aiemmasta normaali ja riittävä unimäärä? </li>
<li>Minkälainen on unirytmi eli milloin nukkumaan, milloin ylös, ja onko rytmi säännöllinen esim. arki vs. viikonloput?</li>
<li>Miten uniongelma vaikuttaa päiväaikaiseen vireystilaan ja toimintakykyyn?</li>
<li>Onko unettomuudesta tullut ”iso asia”, murehtiiko sitä tai jotain muuta?</li>
<li>mahd. unikyselylomakkeiden hyödyntäminen: ISI, BNSQ tmv</li>

  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="c"
          data-hide-label="c - Piilota vastaus">
    c
  </button>
  <div class="solution-content">

<li>Ensiksi on tärkeää kertoa unettomuuden yleisyydestä ja toteuttaa asian normalisoimista (osa normaalia elämää); siis yleistä ”stigman vähentämistä”</li>
<li>Annetaan perustietoa unen mekanismeista ja funktioista (sekä mikä kaikki säätelee unta että mikä merkitys hyvällä unella on mm. päiväaikaisella vireystilalle ja toimintakyvylle, huom. potilaan väsymys ja ärtyneisyys)</li>
<li>Tavallisimmin ei löydy yhtä syytä unettomuuteen, mutta on silti monia tekijöitä, joihin voidaan vaikuttaa ensisijaisesti lääkkeettömin keinoin - toisaalta ymmärtäväisyys sen suhteen, että tämä voi tuntua työläältä tai epämääräiseltä ja siksi turhauttavalta vs. ”quick fix”</li>
<li>Yleisin syy unettomuuteen on elämäntilanteeseen tai -muutoksiin liittyvä kuormitus - näiden purkaminen</li>
<li>Unihygienian pääelementit ja merkitys: unirytmin säännöllisyyden merkitys, päiväaikainen sekä fyysinen että psyykkinen aktiivisuus auttaa, illalla rauhoittuminen riittävän varhain, ei raskasta liikuntaa myöhään, sängyssä vain unta tai seksiä, ellei uni tule mennään pois sängystä, valoisuus, melu, makuuhuoneen lämpötila, kofeiinin välttäminen iltapäivän puolella, päiväunien välttäminen tai niiden riittävän varhaisina ja lyhyinä pitäminen, vaakatasossa vietetyn ajan välttäminen vaikkei nukkuisikaan päiväunia, päihteiden (etenkin alkoholin) unen rakennetta heikentävä vaikutus, nikotiinin vaikutus, hiilihydraattipitoinen iltapala auttaa väsyttävästi, ym. Jos huolia/murheita/stressiä, joiden ajattelee vaikuttavan asiaan, näiden asioiden käsittely hyvissä ajoin ennen nukkumaanmenoa. Sinivalon merkitys tarv. melatoniinia hajottavan mekanismin kertomisen kautta. Aivojen ”ohjelmoiminen” nukkumiseen iltarutiinien ja säännöllisen rytmin kautta, ym.</li>
<li>Kannattaa kertoa unettomuuden taipumuksesta muuttua itseään ruokkivaksi kierteeksi eli katastrofoinnin välttämisen tärkeydestä</li>

Potilaan kanssa yhdessä sen kartoittaminen, mihin muutoksiin hänen olisi helpointa tarttua ja mitkä muutoksista voisivat olla vaikuttavimpia

<li>Konkreettisia menetelmiä yo. muutosten tueksi: unipäiväkirja auttaa hahmottamaan mikä ”mättää”, omahoito-oppaiden tuoma lisätieto ja -apu, älykello/-sormus sopii joillekin tuomaan dataa unen todellisesta kestosta ym.</li>

Testosteronihuolen suhteen huolen validointi, mutta myös tulee motivoivan haastattelun keinoin käydä asiaa läpi

<li>Yleisesti pyrkimys siihen, että potilas itse oivaltaa a) ettei testosteroni ole ratkaisu ja b) että voi omilla toimillaan vaikuttaa oireisiinsa. Ts. tietoa ei ”kaadeta” potilaalle</li>

Ajankäytöstä se, että etenkin jos potilas suhtautuu nihkeästi, jaetaan hoitosuhteen syntymistä osiin ja rakennetaan luottamusta useammalla käynnillä / soitolla / muulla kontaktilla.
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="d"
          data-hide-label="d - Piilota vastaus">
    d
  </button>
  <div class="solution-content">

**Tulosyy: Väsymys, ärtyneisyys**

**Esitiedot:**

48-vuotias mies, ei perussairauksia tai lääkityksiä. 

Työskentelee keskisuuren yrityksen keskijohdossa ja hänellä on vaimo ja kaksi lasta.

Potenut nyt x kk väsymystä ja ärtyneisyyttä. Käynyt oma-aloitteisesti ja omakustanteisesti edeltävästi Puhti-labroissa ja vapaasti laskettu testosteroni on hieman viitearvojen alapuolella. Muut labrat ok. 

Uneensa epätyytyväinen, nukkuu oman arvionsa mukaan n. 4-5 tuntia yössä, koska useampana päivänä viikossa on vaikeaa saada unen päästä kiinni. Työ ja lapset stressaavat. Normaalipainoinen ja pelaa sulkapalloa kaksi kertaa viikossa. Vaimo ei ole huomannut hengenkatkoksia unessa, ei kuorsaa. Kokee väsymystä päivällä ja kokee väsymyksen vaikuttavan työssä suoriutumiseen. Seksuaalitoiminnoissa ei ole huomannut ongelmia.

**Status:** 

Potilas on asiallinen ja orientoitunut, pukeutunut siististi. Tulee katsekontaktiin. Keskustelussa aktiivinen. Ajatus loogista. Jalkaa tärisyttää lattiaan, motoriikka muuten levollista. Mieliala ei kuvaudu alentuneena, kasvoilla on ilmettä. Affektit adekvaatit. Leuka normaalikokoinen. Lihaksikas rakenne. Ei gynekomastiaa. Parta kasvaa hyvin. Ei kuvaudu hypogonadismin merkkejä.

**Suunnitelma:**

Ensijainen työdiagnoosi on ei-elimellinen unettomuus, koska ICD-10-kriteerit täyttyvät: tyytymättömyys unen määrään + nukahtamisvaikeus + unihäiriö aiheuttaa kliinisesti merkittävää haittaa + univaikeus esiintynyt vähintään kolmena yönä viikossa vähintään kuukauden ajan; ei löydy muuta selitystä ongelmille. 

Annettu psykoedukaatiota ja ohjattu unipäiväkirjan pitämiseen. Tällä kartoitetaan tarkemmin uniongelmaa ja siihen vaikuttavia tekijöitä. Potilas kirjaa vähintään vaakatasossa vietetyn ajan, alkoholi- ja kofeiiniannokset ja liikuntakerrat nukkumaanmenoajan ja arvioidun unensaannin lisäksi. Ei tällä kertaa herää epäilyä uniapneasta potilaan kertoman ja statuksen perusteella, mutta jos myöhemmin herää epäily (esimerkiksi vaimo ilmoittaakin hengityskatkoksista), niin yöpolygrafiaharkinta silloin. Keskusteltu tarpeesta unilääkkeelle, mutta potilas ei tällaista nyt halua. Ei myöskään koe tarvetta unihoitajan käynnille. Ei myöskään kokenut tarvetta nettiterapialle tai työterveyden unikoululle. Annettu linkki Mielenterveystalon unettomuuden omahoito-ohjelmaan. Potilas ei antanunt lupaa ottaa yhteyttä työterveyshuoltoon työkuvan muuttamiseksi/keventämiseksi. 

Kontrolli 4 viikon päästä soitolla, kysellään silloin unen parantumisesta. Palataan silloin myös testosteroni-asiaan ja harkitaan tuloksen kontrollointia, jos elintavat on saatu kuntoon. 
  </div>
</div>

### Alkoholinkäyttö lisääntynyt työttömällä

Terveyskeskusvastaanotollesi tulee 32-vuotias mies avovaimonsa kehotuksesta. Potilas kertoo olleensa viime aikoina tavanomaista kireämpi ja ärtyneempi. Hän toivoisi jotakin rauhoittavaa lääkitystä. Esitietoja kartoittaessasi käy nopeasti ilmi, että potilas on joutunut puoli vuotta sitten työttömäksi ja sen jälkeen ollut pääosin kotona. Töiden päättymisen jälkeen potilaan alkoholinkäyttö on lisääntynyt. Aiemminkin, koko aikuisiän ajan, potilas on käyttänyt alkoholia lähes joka viikonloppu humalahakuisesti, mutta nyt alkanut juomaan myös arkipäivisin, ja viimeisen 3 kk:n aikana juonut päivittäin vähintään 6 ravintola-annosta olutta. Viikonloppuisin käytetyt määrät olleet selvästi runsaampia. Kun avovaimo kiinnittänyt huomiota potilaan alkoholinkäyttöön, asiasta tullut riitaa ja tämän jälkeen potilas alkanut menettää hermonsa aivan pienistäkin asioista. Potilaan olo ollut muutenkin ahdistuneempi ja yöuni muuttunut katkonaiseksi.

- a) Millä kysymyksillä jatkaisit potilaan alkoholinkäytön selvittelyä? Tekisitkö jotakin tutkimuksia ja miten perustelisit ne potilaalle?
- b) Miten ottaisit potilaan alkoholinkäytön puheeksi? Minkälaista psykoedukaatiota antaisit tälle alkoholinkäyttöön liittyen?

Vastaanotolla käydyn keskustelun lopuksi potilas toteaa, että hän haluaisi yrittää vähentää alkoholinkäyttöään.

- c) Miten kertoisit potilaalle lyhyesti alkoholiongelmaan tarjolla olevista hoitovaihtoehdoista?

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

Jatkokysymyksiä (2 pistettä, jos 4 alla olevista mainittu)

<li>Aiempi alkoholinkäyttöhistoria</li>
<li>Viikonloppujuomisen tarkka määrä</li>
<li>Kokeeko potilas juomisen hallinnan vaikeaksi?</li>
<li>Alkoholin vaikutus sosiaaliseen elämään ja työelämään</li>
<li>Miten potilas ajattelee alkoholin vaikuttavan kuvaamaansa ahdistuneisuuteen, ärtyneisyyteen ja uniongelmiin?</li>
<li>Alkoholinkäyttöön liittyvät terveydelliset haitat, tapaturmat, muistikatkot jne.</li>


**Näiden kysymysten kautta voi jo pitkälti arvioida, täyttyykö alkoholiriippuvuuden tai haitallisen käytön diagnostiset kriteerit.** Kun siis puhutaan päihdehäiriöistä (ICD-10), puhutaan joko haitallisesta käytöstä tai riippuvuudesta. Haitallisessa käytössä päihteen käyttöön liittyy selvästi määriteltävissä olevia fyysisiä tai psyykkisiä haittoja, mutta ei vielä diagnostista riippuvuutta. 

<li>Haitallinen käyttö:</li>
  <ul>
   <li>1 - Diagnoosiin vaaditaan, että käyttäjälle on aiheutunut todellinen mielenterveyden tai ruumiillisen terveyden vaurio. Haitan luonne tulee olla selvästi todettavissa</li>
   <li>2 - Aineen käyttö kestänyt vähintään 1kk tai tapahtunut toistuvasti edellisen 12 kk aikana</li>
   <li>3 - Oire ei selity muilla mielenterveyden häiriöillä tai käyttäytymisen häiriöllä (poikkeuksena äkillinen päihtymystila)</li>
 </ul>

<li>Päihderiippuvuus:</li>
  <ul>
   <li>Vähintään 3 seuraavista oireista ovat esiintyneet yhtäaikaisesti vähintään kuukauden ajan, tai mikäli yhtämittaiset jaksot ovat kuukautta lyhyempiä, ne on todettu toistuvasti viimeksi kuluneen vuoden aikana</li>
      <ul>
        <li>Toleranssi</li>
        <li>Kontrollin menetys</li>
        <li>Pakonomaisuus/Himo</li>
        <li>Vieroitusoireet</li>
        <li>Ajankäyttö</li>
        <li>Käyttö jatkuu haitoista huolimatta</li>
      </ul>
  </ul>

---

Alkuvaiheen alkoholiongelman selvittelyssä käytettyjä tutkimuksia (2 pistettä, jos AUDIT ja lab. kokeet mainittu perusteluineen)

<li>AUDIT</li>
  <ul>
   <li>AUDIT:n täyttämistä voi perustella sillä, että saadun pistemäärän perusteella potilaan alkoholinkäyttöön liittyviä riskejä voidaan verrata lääketieteelliseen tutkimustietoon. AUDITin sensitiivisyys ja spesifisyys ovat lähes 90 %.</li>
 </ul>

<li>Lab. kokeet: (PVK, K, Na, Krea), B-PEth, ALAT, GT (CDT, GT-CDT-indeksi)</li>
  <ul>
   <li>Lab. kokeita voi perustella esim. sillä, että niistä saadaan suuntaa antava käsitys siitä, kuinka paljon alkoholinkäyttö kuormittaa potilaan maksaa, ja toisaalta niiden avulla voidaan seurata hoidon onnistumista. Lyytit ja PVK voisivat olla hyvä ottaa ihan yleisitilaa arvioivina tutkimuksina.</li>
    <li>PEth on sensitiivisin (98–100 %) ja spesifisin (94–100 %) osoittamaan pitkäaikaista runsasta alkoholinkäyttöä (päivittäinen alkoholiannos yli 5 ravintola-annosta). Muiden tutkimusten (MCV, ALAT, ASAT, GT, CDT) sensitiivisyys ja spesifisyys on huono (30–40 %), eikä niitä tulisi käyttää päätöksentekoon, jolla voi olla sosiaalisia, taloudellisia tai juridisia vaikutuksia potilaalle.</li>
 </ul>
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

Puheeksiotto ja suhtautuminen (2 pistettä, jos 2 alla olevista kohdista mainittu)

<li>Lämmin, empaattinen, tuomitsematon ja kannustava suhtautuminen tärkeää</li>
<li>Mieluummin kysytään potilaalta, mitä tämä ajattelee alkoholinkäytöstään tai onko tämä ajatellut vähentää alkoholinkäyttöään, kuin annetaan suora kehotus vähentää juomista</li>
<li>Korostetaan potilaan omaa vastuuta päätöksenteosta, mutta myös sitä, että apua juomisen lopettamiseen on tarjolla</li>

---

Mallivastauksessa siis korostetaan mini-intervention periaatteita, jotka voi muistaa RAAMIT-muistisäännöstä, joka myötäilee yleisestikin motivoivan haastattelun periaatteita. Motivoivassa haastattelussa vältetään valmiiden ratkaisuiden tarjoamista ja pyritään löytämään potilaslähtöisesti niitä seikkoja, jotka puoltaisivat terveyden kannalta myönteisten muutosten tekemistä.

<li>R = Rohkeus: Korostetaan, että apua juomisen lopettamiseen on tarjolla ja se on todellakin mahdollista</li>
<li>A = Alkoholitietous: Psykoedukaatio alkoholinkäytön haitoista. Kerrotaan riskitasot (viikko- ja päivätasolla), yleiset terveydelliset haitat ja mahdolliset vaikutukset juuri kyseisen potilaan psyykkisiin oireisiin</li>
<li>A = Apu: Tarjolla on monia hoitomuotoja (lääkehoito (antabus, opioidireseptorisalpaajat), psykososiaalinen hoito (keskusteltukäynnit esim. psykiatrisen sairaanhoitajan vo:lla tai A-klinikalla, kognitiivinen käyttäytymisterapia, pari- ja perheterapia, AA-ryhmät, omahoito netin ohjeiden kautta), katkaisuhoito (avokatkaisuhoito, laitoskatkaisuhoito).</li>
<li>M = Myötätunto: Lämmin, empaattinen, tuomitsematon ja kannustava suhtautuminen tärkeää</li>
<li>I = Mieluummin kysytään potilaalta, mitä tämä ajattelee alkoholinkäytöstään tai onko tämä ajatellut vähentää alkoholinkäyttöään, kuin annetaan suora kehotus vähentää juomista</li>
<li>T = Toimintaohjeet: Sovitaan potilaalle yksilöllisesti sopivasta vähentämisstrategiasta</li>

--- 

Toinen osa kysymystä oli antaa psykoedukaatiota, josta vastaa RAAMIT-säännön alkoholitietous-osio. (2 pistettä, jos 2 alla olevista kohdista mainittu)

<li>Alkoholinkäytön riskitasot (viikko- ja päivätasolla)</li>
  <ul>
   <li>Korkean riskin (sairastavuus ja kuolleisuus nousee merkittävästi) rajana on miehillä 23-24 annosta viikossa / säännöllisesti päivittäin 3 annosta tai kertakäyttö yli 6-7 annosta joka viikko (naisilla taas 12-16 annosta viikossa / säännöllisesti päivittäin 2 annosta tai kertakäyttö vähintään 5 annosta joka viikko</li>
   <li>Kohtalaisen riskin rajat (GT-arvo lähtee jo nousemaan) ovat miehillä 14 annosta ja naisilla 7 annosta viikossa</li>
 </ul>
<li>Alkoholin yleiset terveydelliset haitat</li>
  <ul>
   <li>Kohonnut sairastumisriski melkein kaikelle: ylipaino, kohonnut verenpaine, rytmihäiriöt, maksasairaus, dementia, aivoverenvuodot, päänsärky, krapula, kouristukset, unettomuus, hormonihäiriöt ja seksuaalivaikeudet, tapaturmat, syöpäriski (esim. suun, kurkunpään, ruokatorven), psykiatriset häiriöt (masennus, ahdistus), uniapnean paheneminen...</li>
 </ul>
<li>Alkoholin mahdolliset vaikutukset juuri kyseisen potilaan kuvaamiin psyykkisiin oireisiin</li>
  <ul>
   <li>Potilaan olo ollut ahdistunut, hänen pinnansa on kireällä ("alkanut menettää hermonsa aivan pienistäkin asioista") ja yöuni on muuttunut katkonaiseksi.</li>
   <li>Potilaan kuvaama ahdistus voimistuu varmasti merkittävästi "nousuhumalan" jälkeen ja krapulassa, kun alkoholin vaikutus lakkaa ja syntyy aikaisempaa lamaava vaikutusta kompensoiva stimuloivasti kompensatorinen vaihe.</li>
   <li>Jos potilas käyttää alkoholia "rentoutumiseen", hän saattaa huomata olevansa entistä kireämpi heti, kun alkoholi ei ole enää vaikuttamassa</li>
   <li>Unihäiriö on alkoholin selkein fysiologinen haitta. Vaikka alkoholi auttaa nukahtamaan nopeammin, se tuhoaa unen rakenteen ja voi aiheuttaa unen katkonaisuutta. Tämän seurauksena aivot ja keho eivät palaudu. Väsymys taas ruokkii suoraan päiväaikaista ärtyneisyyttä ja ahdistusta. </li>
 </ul>
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="c"
          data-hide-label="c - Piilota vastaus">
    c
  </button>
  <div class="solution-content">

Alkoholiongelman hoitomuotoja (4 pistettä, jos 4 alla olevista alakohdista mainittu; laskettu myös, jos esim. jaotellut lääkehoidon eri lääkkeisiin -> niistä saanut erilleen pisteitä)


<li>Lääkehoito</li>
  <ul>
   <li>Psykososiaaliset hoidot ovat alkoholiriippuvuuden hoidon perusta, mutta tulosta voidaan parantaa lääkityksellä merkittävästi (keskimäärin 15–25 %). Alkoholista riippuvaiset potilaat sitoutuvat usein kuitenkin huonosti lääkehoitoon; tästä huolimatta sitä tulee suositella. </li>
   <li>Vaihtoehtoja on mm. disulfiraami (antabus), opioidiantagonistit (naltreksoni tai nalmefeeni) ja akamprosaatti</li>
 </ul>
<li>Terapeuttinen hoito ja keskustelukäynnit</li>
  <ul>
   <li>Keskustelukäyntejä psykiatrisen sairaanhoitajan vo:lla tai psykologilla tai A-klinikalla; sisältävät motivoivan haastattelun, kognitiivisen psykoterapian tms. elementtejä riippuen hoitavan henkilön koulutuksesta</li>
   <li>Lähetteen vaativa nettiterapia</li>
   <li>Joskus jopa virallinen psykoterapia (esim. kognitiivinen käyttäytymisterapia); voidaan käyttää myös esimerkiksi kuvataide-, musiikki- tai rentoutusterapiaa tai psykodraamaa. Kaikkia hoitoja ei ole saatavissa kaikkialla. Potilaan mielipidettä on syytä kuulla hoitomuodon valinnassa. Hoito edellyttää usein eri hoitopaikkojen yhteistyötä.</li>
 </ul>
<li>AA-ryhmät</li>
  <ul>
   <li>Suositeltavaa vertaistoimintaa</li>
 </ul>
<li>Katkaisuhoito: Avokatkaisuhoito/Laitoskatkaisuhoito</li>
 <ul>
   <li>Avohoitovieroitus tavoiteltua, mutta tarpeen mukaan osastollakin, varsinkin jos aiemmin vaikeita vieroitusoireita, on hoitoa vaativa perussairaus tai itsetuhoisuutta, sekapäihdekäyttö tai ei ole tukiverkostoa kotona.</li>
   <li>Avokatkaisuhoidossa voidaan käyttää lieviin tai keskivaikeisiin vierotusoireisiin valvottua klooridiatsepoksidilääkitystä (25–50 mg x 2–4) pienenevin annoksin 3–5 vuorokauden ajan</li>
   <li>Osastolla taas tarvittaessa diatsepaamikyllästyshoito, jos on vaikeat vieroitusoireet. Jos potilas on jouduttu ottaa osastolle muusta syystä kuin korkeiden CIWA-Ar-pisteiden vuoksi, niin kyllästyshoitoa ei automaattisesti tarvita, vaan voidaan oireiden mukaan yrittää kevyempää hoitoa esim. avovieroitusohjeiden mukaisesti</li>
 </ul>

---

Lyhyesti voisi tiivistää, että alkoholiriippuvuuden hoidon osa-alueet ovat: 

<li>1 Kartoita alkoholinkäyttöä</li>
<li>2 Vaikeusasteen/diagnoosin mukaan anna psykoedukaatiota alkoholin käytöstä ja sen yhteydestä muihin potilaan sairauksiin</li>
<li>3 Arvioi muutosmotivaatio ja voimavarat, pyydä potilasta asettamaan oma tavoite</li>
<li>4 Sovi potilaan kanssa seurannasta ja muista jatkotoimista (esim. vastaanottokäynnit sh/lääkäri, labrat (esim, peth, maksa-arvot, huumeseulaus), ”Juomapäiväkirja”, ajokorttiasiat*)</li>
<li>5 Neuvo omahoito (Esim. paihdelinkki.fi tai mielenterveystalo.fi)</li>
<li>6 Ohjaa psykososiaaliseen hoitoon (päihdehoitajat, lähetteen vaativa nettiterapia, ohjaus mielenterveys- ja päihdeyksikköön, psykoterapiat, AA, yhteisövahvistusohjelma)</li>
<li>7 Tarjoa lääkehoitoa alkoholiriippuvuuden hoitoon</li>
<li>8 Tarvittaessa laitoskatkaisuhoitoon</li>
  </div>
</div>