# 2006 

## Viimeinen

Tähän loppuu tärpit wikissä.

### Kannabiksen merkittävimmät/tärkeimmät vaikutukset keskushermostossa ja periferiassa

<div class="">
  <button class="solution-button"
          data-label="Vastaus"
          data-hide-label="Piilota vastaus">
    Vastaus
  </button>
  <div class="solution-content">

Kannabiksesta puhuttaessa puhutaan yleensä sen tärkeimpiä huumaavia vaikutuksia välittävästä yhdisteestä nimeltä THC (Δ9-tetrahydrokannabinoli). Se vaikuttaa elimistössä pääasiassa endokannabinoidijärjestelmän kautta, erityisesti CB1-reseptorin (keskushermosto) ja CB2-reseptorin (immuunijärjestelmä/periferia) osittaisagonismin kautta. Nämä reseptorit ovat Gi/o-proteiinikytkentäisiä. 

Keskushermostovaikutukset: Verenkiertoon siirryttyään THC läpäisee nopeasti aivojen veri-aivoesteen ja saavuttaa aivojen CB1-reseptorit. CB1-reseptorien stimulaatio estää adenylaattisyklaasia vähentäen cAMP:n pitoisuutta, estää useita Ca2+-kanavia ja aukaisee K+-kanavia. Nämä vaikutukset sopivat presynaptiseen välittäjäaineiden vapautumisen säätelyyn ja hitaaseen hermosolujen toiminnan estoon. CB1-reseptorien sijainti useilla aivoalueilla näyttää liittyvän eri välittäjäaineita käyttäviin neuroneihin, esimerkiksi kolinergisiin hippokampuksessa (asetyylikoliinin vapautumisen esto ja lähimuistin huononeminen) ja dopaminergisiin "mielihyväkeskuksessa" accumbens-tumakkeessa ja caudatus-putamenissa (vapaa dopamiini lisääntyy muun muassa ventraalisella tegmentumin alueella tapahtuvan GABAergisten neuronien inhibition vuoksi). 

<li>Psyykkiset vaikutukset: euforia/rentoutuminen, muuttuneet aistikokemukset; kääntöpuolella voi esiintyä ahdistusta ja vainoharhaisuutta, pahimmassa tapauksessa jopa kunnon kannabispsykoosi</li>
<li>Kognitiiviset vaikutukset: heikentää lyhytkestoista muistia ja oppimiskykyä käytön aikana ja toistuvassa runsaassa käytössä pidempäänkin</li>
<li>Motorinen koordinaatio: vaikutukset pikkuaivoissa ja tyvitumakkeissa johtavat reaktioajan pidentymiseen, tasapainon heikkenemiseen ja hienomotoriikan häiriöihin</li>
<li>Analgesia: kipuratojen modulointi -> kipua lievittävä vaikutus (jotkut käyttävätkin kroonisen kivun hoitamiseen)</li>
<li>Pahoinvoinnin esto</li>
<li>Ruokahalun lisääntyminen (munchies)</li>
<li>Pitkäaikaiskäytössä riippuvuus ja vieroitusoireet (ärtyneisyys, ahdistuneisuus, unettomuus, alentunut ruokahalu, epämääräiset lihaskivut, HR ja RR nousu, hikoilu, lihasnykäykset)</li>


---

Periferia: vaikutukset välittyvät sekä CB1- että CB2-reseptoreiden kautta ja näkyvät useissa elinjärjestelmissä

<li>Sydän ja verenkierto: Takykardia ja vasodilataatio (erityisesti silmien punoitus)</li>
<li>Immuunijärjestelmä: CB2-reseptoreita on runsaasti valkosoluissa ja pernassa. Kannabiksella on todettu olevan anti-inflammatorisia vaikutuksia</li>
<li>Hengitystiet: Lyhytaikaisesti poltettu kannabis voi laajentaa keuhkoputkia, mutta pitkäaikainen käyttö ärsyttää limakalvoja ja lisää kroonisen bronkiitin ja obstruktiivisen keuhkosairauden riskiä</li>

  </div>
</div>


### Touretten sdr

<div class="">
  <button class="solution-button"
          data-label="Vastaus"
          data-hide-label="Piilota vastaus">
    Vastaus
  </button>
  <div class="solution-content">

Touretten oireyhtymä on tunnetuin ns. tic-häiriöistä. Tic-häiriöiden (ICD-10:n suomennoksessa käytetään nimitystä nykimishäiriöt) tunnusomainen piirre on tic-oire, joka on nopea, äkillinen, tarkoitukseton, toistuva ja epäsäännöllinen lihasliike tai äännähdys. Vastoin yleistä uskoa, ei Tourette ole ns. kiroilusairaus, vaan vain pieni osa (noin 10 %) Tourette-henkilöistä kärsii koprolaliasta eli pakonomaisesta säädyttömien sanojen käytöstä. 

<li>Motoriset tic-oireet voivat olla mm. silmien räpyttelyä, irvistelyä, pään nykimistä tai hartioiden kohtauksia</li>
<li>Vokaaliset tic-oireet voiat olla mm. rykimistä, hihkaisua, niiskuttamista tai sanojen/lauseiden toistamista (ekolalia)</li>

Tic-oireet voivat vaihdella ajan myötä – joskus ne pahenevat, joskus vähenevät. Yksi oire voi hävitä kuukausiksi ja korvautua uudella, mutta sitten taas tulla takaisin. Monilla oireet lievittyvät aikuisiässä. 

Monet kuvaavat ennen tikkiä tuntuvaa epämiellyttävää kutinaa, jännitystä tai painetta, joka helpottaa vain suorittamalla kyseinen liike tai ääni. Tikkejä voi usein hillitä hetkellisesti (esim. koulutunnin ajan), mutta se vaatii valtavasti energiaa ja lopulta oireet purkautuvat myöhemmin. Tämän takia Touretten oireyhtymä ja muutkin tic-oireyhtymät voivat muistuttaa pakko-oireista häiriötä ja etenkin lapsuusiässä alkaneissa häiriöissä nämä voivat esiintyä yhdessä. Toimii myös toisin päin: kolmanneksella pakko-oireista häiriötä sairastavista on samanaikaisia tic-oireita. Tourette muutenkin esiintyy harvoin yksin ja OCD:n lisäksi yleisiä komorbiditeetteja ovat mm. ADHD ja ahdistuneisuushäiriöt. 

---

Ei ole parantavaa hoitoa olemassa, mutta oireita voidaan kyllä helpottaa tarvittaessa. Hoitoa tarvitaan vain, jos ne haittaavat toimintakykyä elämässä. Hoitoon kuuluu tärkeimpänä psykoedukaatio, käyttäytymisterapia ja vaikeissa tapauksissa lääkitys. Terapia on siis samaa kuin OCD:n hoidossa eli altistus ja reaktion esto -terapia (ERP), jonka lisäksi yleensä kognitiivista terapiaa. Voidaan tarjota myös verkkovälitteisesti nettiterapiana. ERP:ssä harjoitellaan tic-oireet toteuttamisen välttämistä. Voidaan myös hyödyntää tavankääntämismenetelmää (HRT), jossa opetellaan tunnistamaan ennetuntemus ja tekemään korvaava liike. Ensisijaisena lääkehoitona voidaan terapialle vasteettomissa tilanteissa käyttää antidopaminergisiä lääkkeitä, kuten aripipratsolia tai risperidonia. 

  </div>
</div>

### Dissosiaatiosta 

- a. Mitä tarkoittaa dissosiaatio 
- b. Dissosiaatiohäiriöt

<div class="">
  <button class="solution-button"
          data-label="a"
          data-hide-label="a - Piilota vastaus">
    a
  </button>
  <div class="solution-content">

Dissosiaation keskeisenä piirteenä on tietoisuuden, muistin, identiteetin tai havaintojen integraation hajaannus. Tällöin henkilön kyky toimia tietoisena, kokemisen eri puolia integroivana persoonana on heikentynyt.

Toisin sanoen tästä aiheutuvia tuntemuksia eli dissosiatiivisia oireita ovat mm: 

<li>Depersonalisaatio = oman itsen kokeminen vieraana tai outona (kuin katsoisi elokuvaa itsestään)</li>
<li>Derealisaatio = ympäristön kokeminen vieraana tai outona (kuin olisi unessa)</li>
<li>Ajan ja paikan tajun kadottaminen</li>
<li>Muistissa voi olla aukkoja (esim. ajaa töistä kotiin, mutta ei muista mitään ajomatkasta)</li>

---

Kannattaa huomioida, että dissosiaatiokokemukset ja dissosiaatiohäiriöt voi helposti sekoittaa psykoosiin. Dissosiaatiossa ihminen voi tuntea maailman epätodelliseksi (derealisaatio), mutta hän tietää, että kyse on vain tunteesta tai tunnistaa häiriön (esim. amnesiassa). Realiteettitestaus on siis tallella toisin kuin psykoosissa. Toisin sanoen psykoottinen henkilö yleensä kokee hallusinaationsa ja harhaluulonsa selvästi tosiksi, kun taas dissosiaatiohäiriöinen henkilö tunnistaa virheelliset kokemukset tai ei ole varma siitä, mikä hänen ympäristössään ja kokemusmaailmassaan on totta ja mikä ei. 
  </div>
</div>

<div class="">
  <button class="solution-button"
          data-label="b"
          data-hide-label="b - Piilota vastaus">
    b
  </button>
  <div class="solution-content">

**Dissosiaatio ei ole aina häiriöllistä ja kaikilla ihmisillä on dissosiatiivisia kokemuksia aika ajoin.** Lievä dissosiaatio (esim. ajatuksiin uppoutuminen lukiessa (ei kuule nimeään huudettavan), “automaattiohjaus” ajaessa kotiin töistä, deja vu-kokemukset yms.) ovat täysi normaaleja asioita. Usein myös dissosiaatio liittyy psyykkiseen stressiin tai traumaan, ja sitä pidetään eräänlaisena psyykkisenä suojamekanismina (esim. depersonalisaatiokokemus kuullessaan syöpädiagnoosistaan). Se ei tällöinkään aina ole häiriöllistä, vaan voi olla normaalin reaktion tasoista useimmilla. _Jos taas dissosiatiiviset oireet säilyvät pitkään ja tuottavat haittaa, puhutaan dissosiatiivisesta häiriöstä._

Dissosiaatiohäiriöt kehittyvät usein toistuvan traumatisoitumisen tai vakavan kiintymyssuhdehäiriön seurauksena. Dissosiaatiohäiriöiden diagnosointi perustuu anamneesiin ja statukseen. Diagnostiikka on varmempaa, mikäli voidaan todella tarkkailla ja haastatella potilasta oireiston aikana eikä oirekuvaus ole pelkästään anamnestinen. Omaisten haastattelu ja muu tiedonkeruu muista lähteistä kuin potilaalta itseltään ovat usein ratkaisevan tärkeitä. 

Häiriöiden luokittelu on täysin erilaista ICD-10:n, ICD-11:n ja DSM-5:n välillä. DSM-5:n luokittelu on kuitenkin simppelein, joten esittelen sen tärkeimmät häiriötyypit: dissosiatiivinen identiteettihäiriöt (DID), dissosiatiivinen amnesia (jonka alaryhmänä dissosiatiivinen pakkovaellus (fugue)) ja depersonalisaatio/derealisaatiohäiriö. 

Yleinen diagnostinen kriteeri kaikille häiriöille on se, että häiriöt eivät ole huumeiden/päihteiden suorista vaikutuksista tai ruumiillisista häiriöistä (esim. epilepsia tai pään vammat) johtuvia.

---

Dissosiatiivinen identiteettihäiriö (DID) tarkoittaa, että henkilöllä on vähintään kaksi erilaista identiteettiä tai persoonallisuuden tasoa (ja kullakin oma, suhteellisen kiinteä tapansa hahmottaa itseään ja ympäristöään ja suhtautua niihin). Vähintään kaksi näistä identiteeteistä tai persoonallisuuden tasoista ottaa toistuvasti vallan henkilön käyttäytymisessä. Persoonallisuudet saattavat tietää toisistaan tai vain joku niistä voi tietää toisista yms. Identiteettien välillä voi olla muistikatkoja. Yleisesti henkilöllä on käsitys omasta, vaikkakin hajanaisesta, identiteetistään. 

Voi ajatella, että trauman seurauksena henkilö kehittää toisen persoonallisuuden alkuperäisen rinnalle, jotta alkuperäisen persoonallisuuden ei tarvitse absorboida kaikkea traumaa. 

--- 

Dissosiatiivisessa amnesiassa tärkein piirre on  yksi tai useampi jakso, jonka aikana henkilö ei kykene palauttamaan mieleensä hänelle tärkeää, usein luonteeltaan traumaattista tai stressin sävyttämää tietoa, ja häiriö on liian laaja ollakseen tavallista unohtelua. 

Häiriön erityismuoto on dissosiatiivinen pakkovaellus (dissociative amnesia with fugue, dissociative fugue), jossa potilas muuttaa paikkakuntaa alkaen elää yleensä vaatimatonta, huomiota herättämätöntä, mutta normaalilta vaikuttavaa elämää, kykenemättömänä muistamaan aiempia vaiheitaan. Päinvastoin kuin muistinmenetyspotilas, hän on myös kykenemätön huomaamaan tätä muistinmenetystä. Tilan äkillisesti loppuessa, joskus vasta vuosien kuluttua, potilas tyypillisesti muistaa aiemmat elämänvaiheensa, mutta ei elämäänsä vaellusvaiheen aikana.

---

Depersonalisaatio/derealisaatiohäiriössä potilas kokee jatkuvia tai toistuvia depersonalisaatio- tai derealisaatiokokemuksia. Kuten mainittiin aikaisemmin, niin tilapäisinä ja hetkellisinä kokemuksina ne ovat yleisiä ja normaaleja, mutta häiriöstä voidaan puhua, kun kokemukset ovat oireina kliinisesti kuormittavia ja toimintakykyä rajoittavia.

---

Dissosiaatiohäiriön ensiapuna on keskeistä käyttää asiallisen tiedon antamista. Potilaalle on diagnoosin teon jälkeen tehtävä selväksi, että kyse ei ole mielisairaudesta tai etenevästä aivosairaudesta. Muistikatkosten aikaisten tapahtumien selvittäminen luotettaviksi arvioitujen silminnäkijöiden avulla voi suuresti rauhoittaa potilasta.

Tärkein hoitomuoto on psykoterapia. Tavoitteena on, että ihminen voisi kohdata vaikeisiin traumaattisiin kokemuksiin liittyneet muistot ja tunteet, esimerkiksi jakamalla ne toisen ihmisen kanssa, kuten psykoterapiassa. Samalla muistoille syntyy merkitys ja paikka nykypäivän elämässä. Niin ympäristön kuin hoitosuhteenkin on oltava turvallinen ja luotettava.

Lääkehoito on toissijaista ja sitä käytetään pääasiassa komorbiditeettien hoitoon. Esimerkiksi ahdistus ja masennus on dissosiatiivisista oireista kärsivillä tavallista.

  </div>
</div>